In [102]:
import numpy as np

The Basics


Creating Array From List

In [103]:
# Create Array Of [3,6,8,53,7,3] using np.array() function
a = np.array([3,6,8,53,7,3])
print(a)

[ 3  6  8 53  7  3]


In [104]:
b = np.array([[7,5,3,6],[35,8,4,2]])
print(b)

[[ 7  5  3  6]
 [35  8  4  2]]


In [105]:
c = np.array([[7.94,6,3,7.82,2.63],[9,37,8,3,8]])
print(c)

[[ 7.94  6.    3.    7.82  2.63]
 [ 9.   37.    8.    3.    8.  ]]


Dimension Of Array

In [106]:
a.ndim

1

In [107]:
b.ndim

2

____________________________________________________________________________________________________________________________

Find Shape 

In [108]:
# No Of Element In Rows and Column Array
# Gives No Of Element In 1st Row/Column Of 1D Array 
# Gives No Of Elements In Rows And Columns Of 2D Array
# Gives No Of Element Of Rows , Columns And Height Of 3D Array


In [109]:
# Using .shape to find shape/no of element in particular dimension
a.shape


(6,)

In [110]:
b.shape

(2, 4)

____________________________________________________________________________________________________________________________

Data Type Of Array's Element(Actually Here Data Type Means data type and memory space allocated for it)

In [111]:
# Data Type and Space Allocated For 'a' matrix 
a.dtype

dtype('int32')

In [112]:
# For 'b'
b.dtype

dtype('int32')

In [113]:
# For 'c'
c.dtype

dtype('float64')

In [114]:
# You Can Also Change Data Type If Possible 
# While Creating Array 
# a = np.array([8,9,6] , dtype = 'int16') 
# Helps To Manage Memory Effectively


____________________________________________________________________________________________________________________________

ItemSize Of Element Of Array

In [115]:
# Item Size Is Size/Memory Allocated For Element In Given Array In Bytes
# Depends On dtype of array
a.itemsize

4

In [116]:
b.itemsize

4

In [117]:
c.itemsize

8

As Float Takes double The memory than int so it prints 8 instead of 4

____________________________________________________________________________________________________________________________

Size / ItemSize 

.size gives total no of element in array

In [118]:
a.size

6

In [119]:
b.size

8

In [120]:
c.size

10

____________________________________________________________________________________________________________________________


Total Size Of Array 

it can be calculated using .nbytes or simple maths calculation like  a.size*a.itemsize

In [121]:
# Total Memory Required For Whole Array 'a'
a.nbytes

24

In [122]:
# Same As Above But In Mathematical Terms
a.size * a.itemsize

24

In [123]:
# Total Memory Required For Whole Array 'b'
b.nbytes

32

In [124]:
c.nbytes # This Will Give Output As 80

80

# Accessing/Changing Specific Elements,rows,columns in Array

In [125]:
a = np.array([[1,3,5,7,4,3,8],[0,7,5,3,7,4,2]])

In [126]:
# Get Specific Element 
# You Can Access Specific Element in Array By Using Indexing Same As In Python List

print(a[1,6])

2


In [127]:
# Get Specific Row 
a[1,:]

array([0, 7, 5, 3, 7, 4, 2])

In [128]:
# Get Specific Column
a[:,3]

array([7, 3])

In [129]:
# Get Complex Output 
# By Using List Slicing [start_index:end_index:step]

In [130]:
# Let We Want Element From 2 to 5 of second column

a[1,2:6:1]

array([5, 3, 7, 4])

Also We Have Seen Slicing Can Also Be Used Here So We Can Do Same Type Of Operation We Were Performing on List 

In [131]:
# Some Of Slicing Practice

a[0,1:-2:2]

array([3, 7])

In [132]:
a[0,2:6:2]

array([5, 4])

In [133]:
a[0,1:-1:2]

array([3, 7, 3])

In [134]:
# Changing Array Element
a[1,3] = 78

Changing Whole Column/Row Element To One Common Element Or Iterate From List/Array

In [135]:
a[0,:]=2
print(a)

[[ 2  2  2  2  2  2  2]
 [ 0  7  5 78  7  4  2]]


In [136]:
a[0,:]=[1,2,3,4,5,6,7]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 0  7  5 78  7  4  2]]


Accessing Element In 3D Array Is Done By Working Outside In Way

In [137]:
c = np.array([[[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]],[[15,16,17,18,19,20,21],[22,23,24,25,26,27,28]]])
print(c)

[[[ 1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14]]

 [[15 16 17 18 19 20 21]
  [22 23 24 25 26 27 28]]]


In [138]:
# Let's Access 9 From 3D Array

c[0,1,1]

9

If You Want To Change Element You Can Use Same Array Operation To Change Elements In Array

You Can Also Change Whole Matrix     

Just Access The Matrix You Want To Change And Add New Matrix

In [139]:
# Let's Change 24 to 29

c[1,1,5] = 29

In [140]:
print(c)

[[[ 1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14]]

 [[15 16 17 18 19 20 21]
  [22 23 24 25 26 29 28]]]


In [141]:
# Change whole Inner Matrix To New Matrix 
c[1,:,:] = [[22,23,24,25,26,27,28],[29,30,31,32,33,34,35]]
print(c)

[[[ 1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14]]

 [[22 23 24 25 26 27 28]
  [29 30 31 32 33 34 35]]]


But Remember Changing Elements Or Array To A Different Size Or Dimensions Result In Error 

In [142]:
c[1,:,:] = [[4,5,6],[9,0,7]]

ValueError: could not broadcast input array from shape (2,3) into shape (2,7)

____________________________________________________________________________________________________________________________

# Initializing Different Types Of Arrays

In [ ]:
# All Zero's Matrix
np.zeros(4)

array([0., 0., 0., 0.])

.zeros take argument an int or tuple to specify shape and dimension of array of zeros also you can specify dtype of it

In [ ]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((2,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
np.zeros((6,7,5,1,3))

array([[[[[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]]],


        [[[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]]],


        [[[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]]],


        [[[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]]],


        [[[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]]],


        [[[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]]],


        [[[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]]]],



       [[[[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]

You Can Create Multiple Type Of Arrays of zeros using its function .zeros()

____________________________________________________________________________________________________________________________

In [ ]:
# All 1s Matrix
# This Also Takes One 
np.ones((8,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.ones((7,8,5,4),dtype = 'int16')

array([[[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        ...,

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]],


       [[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
  

To Generate A Matrix Of Same Data Type You Can Use .full() function 

it takes two argument primarily one is shape and dimension another is for element you want to fill in it

In [ ]:
# All Xs Matrix
np.full((3,4),3)
# Again Here You Can Change dtype of matrix 

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [ ]:
# We Use full_like() function to Generate a matrix of same size as another matrix but with a common element at all places

np.full_like(a,2)

array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

In [ ]:
np.full(a.shape,2)

array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

In [ ]:
# Random Decimal Number
np.random.rand(4,2)*100

array([[71.00063721,  2.28668633],
       [17.39816689, 38.67701648],
       [62.76799463, 61.41123726],
       [70.6631028 , 47.68388368]])

In [ ]:
# Random Number On A Older Matrix's Shape
np.random.random_sample(a.shape)

array([[0.41475016, 0.008925  , 0.86958923, 0.36020162, 0.31592417,
        0.82074094, 0.84024807],
       [0.05837808, 0.86959851, 0.58101656, 0.86179352, 0.08215401,
        0.13369552, 0.97922323]])

In [ ]:
# Random Integers Values
np.random.randint(4,9,size=(3))

array([6, 5, 8])

In [ ]:
#Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Repeat an Array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
# Practice Set Q1
arr1 = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
arr1[1:4,1:4] = z
print(arr1)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Python's Rule 1 :- Every Thing Is Reference of Main Object

In [ ]:
a = np.array([1,2,3])
b = a.copy()
print(b)
b[0] = 100
print(b)
print(a)

[1 2 3]
[100   2   3]
[1 2 3]


____________________________________________________________________________________________________________________________

# Mathematics

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
# Addition 
# Adding Scaler To Array Leads To Add Scaler To Every Element Of Array

a + 2

array([3, 4, 5, 6])

In [ ]:
# Substraction 
# Same As Addition
a - 2

array([-1,  0,  1,  2])

In [ ]:
# Multiplication 
# Also Same

a*2

array([2, 4, 6, 8])

In [ ]:
# Division
# Same As Above
a/2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
# Additing Another Array To Original
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [ ]:
# Exponents Of Element Of Matrix
a ** 2

array([ 1,  4,  9, 16])

In [ ]:
# Trigonometrical Function
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


# Linear Algebra

In [ ]:
# We Are Going To Try Matrix Multiplication

a = np.ones((2,3))
print(a)

b= np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
# Determinant of matrix

c = np.identity(3)
# I Have Used Identity Matrix To Check The Determinant Is 1 or not 
np.linalg.det(c)

1.0

# Statistics
  

In [ ]:
stats = np.array([[1,2,3],[4,5,3]])
print(stats)

[[1 2 3]
 [4 5 3]]


In [ ]:
# Mean Of Data In NumPy
np.mean(stats)

3.0

In [ ]:
# Max In Array
np.max(stats)

5

In [ ]:
# Min In Array
np.min(stats)

1

In [ ]:
# Sum Of All Element In Array
np.sum(stats)

18

In [ ]:
# We Can Use Different Function To Calculate Same Output But Numpy has its own function
print((np.sum(stats)/stats.size))

3.0


In [ ]:
# Introduction Of Axis In Picture
# In NumPy, `axis` defines **the direction in which an operation is applied**.
# 1D Array Only Has One Axis (Axis = 0)
# 2D Array Have 2 Axis (Axis = 0 for column-vice operation , Axis = 1 for row-vice operation)
'''row-vice axis tells the function to operate in row format means apply operation on elements which are traversed 
row vice ex axis = 0 for 2D Array'''
np.sum(stats,axis=1)

array([ 6, 12])

Axis Represents In Which Dimension Function Should Work 

For Example Above np.sum(stats,axis = 1) gives addition of element in columns-form

# Reorganizing Arrays

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(before.shape)

(2, 4)


In [ ]:
# Convert array of shape (2,4) to (8,1)
# Be Careful Number Of Element Must Be Same 
# When Converting To Another Shape
# Or When Every reshaping Check Product Of Dimension Of Shape if Both Number Are Equal Then We Can reshape original 

In [ ]:
after = before.reshape(8,1)
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [ ]:
after = np.reshape(before,shape = (2,2,2))
print(after)

TypeError: reshape() got an unexpected keyword argument 'shape'

In [ ]:
a = np.array([[3,4,6,4],[6,3,1,5]])
b = np.array([[5,6,3,2],[5,6,3,2]])

a.sum(axis=1)

array([17, 15])

In [ ]:
# Vertically Stacking Vectors
v1 = np.array([[1,2],[3,4]])
v2 = np.array([[5,6],[7,8]])

np.vstack((v1,v2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
# Horizontal Stack
h1 = np.array([[1,2],[3,4]])
h2 = np.array([[5,6],[7,8]])

np.hstack((h1,h2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
# Vertical Stacking Result A Array Where Element Of Previous Array Are Stacked on top of each other by following rule of
# first traversed will be on top
# Arrays must have the **same number of columns**.
# Think of it as stacking rows **one under the other**

# Miscellaneous

Load Data From File 

In [ ]:
filedata = np.loadtxt('C:/Users/user/DS/datafile.csv' ,delimiter=' ')
print(filedata)

FileNotFoundError: C:/Users/user/DS/datafile.csv not found.

In [ ]:
import os
print(os.getcwd())

c:\Users\user\DS\NumPy


In [143]:
with open("datafile.txt","r")as f :
    print(f.readlines())
    array = f

['42,21,19,29,12,89,48,59,24,34,56,39,4,14,98,86,78,31,73,84,99,58,98,24,\n', '31,32,66,36,82,70,4,16,71,62,90,12,2,18,6,22,12,47,0,33,52,91,99,54,\n', '29,43,75,27,60,71,73,22,4,67,29,23,88,6,55,4,4,73,0,39,96,49,72,79,\n', '13,22,14,99,7,18,69,16,4,98,32,89,27,75,15,53,67,65,48,84,8,2,14,32,\n', '32,46,75,12,86,75,6,63,97,31,94,58,13,23,52,35,3,64,40,95,31,1,30,58,\n', '5,4,13,41,75,38,73,44,82,31,3,40,13,58,62,70,15,60,74,13,34,42,93,84,\n', '38,55,62,87,10,43,0,30,90,51,55,1,54,12,62,30,51,74,69,86,78,51,57,55,\n']


In [144]:
print(array)

<_io.TextIOWrapper name='datafile.txt' mode='r' encoding='utf-8'>


In [162]:
data = np.genfromtxt('datafile.txt',delimiter = ',',dtype = 'int16')
data

array([[42, 21, 19, 29, 12, 89, 48, 59, 24, 34, 56, 39,  4, 14, 98, 86,
        78, 31, 73, 84, 99, 58, 98, 24],
       [31, 32, 66, 36, 82, 70,  4, 16, 71, 62, 90, 12,  2, 18,  6, 22,
        12, 47,  0, 33, 52, 91, 99, 54],
       [29, 43, 75, 27, 60, 71, 73, 22,  4, 67, 29, 23, 88,  6, 55,  4,
         4, 73,  0, 39, 96, 49, 72, 79],
       [13, 22, 14, 99,  7, 18, 69, 16,  4, 98, 32, 89, 27, 75, 15, 53,
        67, 65, 48, 84,  8,  2, 14, 32],
       [32, 46, 75, 12, 86, 75,  6, 63, 97, 31, 94, 58, 13, 23, 52, 35,
         3, 64, 40, 95, 31,  1, 30, 58],
       [ 5,  4, 13, 41, 75, 38, 73, 44, 82, 31,  3, 40, 13, 58, 62, 70,
        15, 60, 74, 13, 34, 42, 93, 84],
       [38, 55, 62, 87, 10, 43,  0, 30, 90, 51, 55,  1, 54, 12, 62, 30,
        51, 74, 69, 86, 78, 51, 57, 55]], dtype=int16)

In [163]:
# Boolean Masking
# Advanced Indexing
data>50

array([[False, False, False, False, False,  True, False,  True, False,
        False,  True, False, False, False,  True,  True,  True, False,
         True,  True,  True,  True,  True, False],
       [False, False,  True, False,  True,  True, False, False,  True,
         True,  True, False, False, False, False, False, False, False,
        False, False,  True,  True,  True,  True],
       [False, False,  True, False,  True,  True,  True, False, False,
         True, False, False,  True, False,  True, False, False,  True,
        False, False,  True, False,  True,  True],
       [False, False, False,  True, False, False,  True, False, False,
         True, False,  True, False,  True, False,  True,  True,  True,
        False,  True, False, False, False, False],
       [False, False,  True, False,  True,  True, False,  True,  True,
        False,  True,  True, False, False,  True, False, False,  True,
        False,  True, False, False, False,  True],
       [False, False, False, False,

In [164]:
data>=50

array([[False, False, False, False, False,  True, False,  True, False,
        False,  True, False, False, False,  True,  True,  True, False,
         True,  True,  True,  True,  True, False],
       [False, False,  True, False,  True,  True, False, False,  True,
         True,  True, False, False, False, False, False, False, False,
        False, False,  True,  True,  True,  True],
       [False, False,  True, False,  True,  True,  True, False, False,
         True, False, False,  True, False,  True, False, False,  True,
        False, False,  True, False,  True,  True],
       [False, False, False,  True, False, False,  True, False, False,
         True, False,  True, False,  True, False,  True,  True,  True,
        False,  True, False, False, False, False],
       [False, False,  True, False,  True,  True, False,  True,  True,
        False,  True,  True, False, False,  True, False, False,  True,
        False,  True, False, False, False,  True],
       [False, False, False, False,

In [165]:
data[data>50] # This Gives Values Which Are Greater Than 50 or given value

array([89, 59, 56, 98, 86, 78, 73, 84, 99, 58, 98, 66, 82, 70, 71, 62, 90,
       52, 91, 99, 54, 75, 60, 71, 73, 67, 88, 55, 73, 96, 72, 79, 99, 69,
       98, 89, 75, 53, 67, 65, 84, 75, 86, 75, 63, 97, 94, 58, 52, 64, 95,
       58, 75, 73, 82, 58, 62, 70, 60, 74, 93, 84, 55, 62, 87, 90, 51, 55,
       54, 62, 51, 74, 69, 86, 78, 51, 57, 55], dtype=int16)

In [170]:
# identify any value in this data 's columns is greater 80
np.any(data>80,axis=0)

array([False, False, False,  True,  True,  True, False, False,  True,
        True,  True,  True,  True, False,  True,  True, False, False,
       False,  True,  True,  True,  True,  True])

In [171]:
# Here axis = 0 represent row-wise iteration and which every row has any element greater than 80 is stored as true other
# who are'nt are stored as false
# You Can Also Check That All Element are greater than 80 or not using

np.all(data>80,axis=0)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [178]:
# Conditonal Indexing
(data>40) & (data<80)

array([[ True, False, False, False, False, False,  True,  True, False,
        False,  True, False, False, False, False, False,  True, False,
         True, False, False,  True, False, False],
       [False, False,  True, False, False,  True, False, False,  True,
         True, False, False, False, False, False, False, False,  True,
        False, False,  True, False, False,  True],
       [False,  True,  True, False,  True,  True,  True, False, False,
         True, False, False, False, False,  True, False, False,  True,
        False, False, False,  True,  True,  True],
       [False, False, False, False, False, False,  True, False, False,
        False, False, False, False,  True, False,  True,  True,  True,
         True, False, False, False, False, False],
       [False,  True,  True, False, False,  True, False,  True, False,
        False, False,  True, False, False,  True, False, False,  True,
        False, False, False, False, False,  True],
       [False, False, False,  True,

In [180]:
# You Can Also Obtain Numbers which follows this condition bytearray
data[(data>40) & (data<80)]
# or
data[((data>40) & (data<80))]

array([42, 48, 59, 56, 78, 73, 58, 66, 70, 71, 62, 47, 52, 54, 43, 75, 60,
       71, 73, 67, 55, 73, 49, 72, 79, 69, 75, 53, 67, 65, 48, 46, 75, 75,
       63, 58, 52, 64, 58, 41, 75, 73, 44, 58, 62, 70, 60, 74, 42, 55, 62,
       43, 51, 55, 54, 62, 51, 74, 69, 78, 51, 57, 55], dtype=int16)

In [ ]:
# Using Not Operator '~'
(~((data>40) & (data<80)))

array([[False,  True,  True,  True,  True,  True, False, False,  True,
         True, False,  True,  True,  True,  True,  True, False,  True,
        False,  True,  True, False,  True,  True],
       [ True,  True, False,  True,  True, False,  True,  True, False,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True, False,  True,  True, False],
       [ True, False, False,  True, False, False, False,  True,  True,
        False,  True,  True,  True,  True, False,  True,  True, False,
         True,  True,  True, False, False, False],
       [ True,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True, False,  True, False, False, False,
        False,  True,  True,  True,  True,  True],
       [ True, False, False,  True,  True, False,  True, False,  True,
         True,  True, False,  True,  True, False,  True,  True, False,
         True,  True,  True,  True,  True, False],
       [ True,  True,  True, False,

You Can Index with a list in Numpy 

In [167]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a[[1,2,6]]) 
# Here First Square Bracket (Outer) Is for accessing a's array and second one is for generating list of element of array 'a' 
# at given index

[2 3 7]


This Is Different From a[5,6,7] this represents a 3d array who's 5,6,7 th element we are going to access

In [191]:
matrix = np.arange(1,31).reshape(6,5)
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [202]:
matrix[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [203]:
matrix[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [212]:
matrix[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [220]:
i = 0
j = 1
while(j<5):
    print(matrix[i,j])
    i=i+1
    j=j+1


2
8
14
20
