In [55]:
import numpy as np

The Basics


Creating Array From List

In [56]:
a = np.array([3,6,8,53,7,3])
print(a)

[ 3  6  8 53  7  3]


In [57]:
b = np.array([[7,5,3,6],[35,8,4,2]])
print(b)

[[ 7  5  3  6]
 [35  8  4  2]]


In [58]:
c = np.array([[7.94,6,3,7.82,2.63],[9,37,8,3,8]])
print(c)

[[ 7.94  6.    3.    7.82  2.63]
 [ 9.   37.    8.    3.    8.  ]]


Dimenstion Of Array

In [59]:
a.ndim

1

In [60]:
b.ndim

2

____________________________________________________________________________________________________________________________

Find Shape 

No Of Element In Rows and Column Array 

Gives No Of Element In 1st Row/Column Of 1D Array

Gives No Of Elements In Rows And Column Of 2D Array

Gives No Of Element Of Rows , Columns And Height Of 3D Array

In [61]:
a.shape


(6,)

In [62]:
b.shape

(2, 4)

____________________________________________________________________________________________________________________________

Find Type Of Array's Element

In [63]:
a.dtype

dtype('int32')

In [64]:
b.dtype

dtype('int32')

In [65]:
c.dtype

dtype('float64')

You Can Also Change Data Type If Possible 

While Creating Array 


a = np.array([8,9,6] , dtype = 'int16') 

Helps To Manage Memory Effectively

____________________________________________________________________________________________________________________________

ItemSize Of Element Of Array

In [66]:
a.itemsize

4

In [67]:
b.itemsize

4

In [68]:
c.itemsize

8

As Float Takes double The memory than int so it prints 8 instead of 4

____________________________________________________________________________________________________________________________

Size / ItemSize 

.size gives total no of element in array

In [69]:
a.size

6

In [70]:
b.size

8

In [71]:
c.size

10

____________________________________________________________________________________________________________________________


Total Size Of Array 

it can be calculated using .nbytes or simple maths calculation like  a.size*a.itemsize

In [72]:
a.nbytes

24

In [73]:
a.size * a.itemsize

24

In [74]:
b.nbytes

32

In [75]:
c.nbytes # This Will Give Output As 80

80

Accessing/Changing Specific Elements,rows,columns

In [76]:
a = np.array([[1,3,5,7,4,3,8],[0,7,5,3,7,4,2]])

In [77]:
# Get Specific Element 
# Format array[r,c]
print(a[1,6])

2


In [78]:
# Get Specific Row 
a[1,:]

array([0, 7, 5, 3, 7, 4, 2])

In [79]:
# Get Specific Column
a[:,3]

array([7, 3])

In [80]:
# Get Complex Output 
# By Using List Slicing [start_index:end_index:step]

In [81]:
# Let We Want Element From 2 to 5 of second column

a[1,2:6:1]

array([5, 3, 7, 4])

Also We Have Seen Slicing Can Also Be Used Here So We Can Do Same Type Of Operation We Were Performing on List 

In [82]:
# Some Of Slicing Practice

a[0,1:-2:2]

array([3, 7])

In [84]:
a[0,2:6:2]

array([5, 4])

In [85]:
a[0,1:-1:2]

array([3, 7, 3])

In [86]:
# Changing Array Element
a[1,3] = 78

Changing Whole Column/Row Element To One Common Element Or Iterate From List/Array

In [91]:
a[0,:]=2
print(a)

[[ 2  2  2  2  2  2  2]
 [ 0  7  5 78  7  4  2]]


In [96]:
a[0,:]=[1,2,3,4,5,6,7]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 0  7  5 78  7  4  2]]


Accessing Element In 3D Array Is Done By Working Outside In

In [97]:
c = np.array([[[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]],[[15,16,17,18,19,20,21],[22,23,24,25,26,27,28]]])
print(c)

[[[ 1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14]]

 [[15 16 17 18 19 20 21]
  [22 23 24 25 26 27 28]]]


In [98]:
# Let's Access 9 From 3D Array

c[0,1,1]

9

If You Want To Change Element You Can Use Same Array Operation To Change Elements In List 

You Can Also Change Whole Matrix Just Access The Matrix You Want To Change And Add New Matrix

In [99]:
# Let's Change 24 to 29

c[1,1,5] = 29

In [100]:
print(c)

[[[ 1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14]]

 [[15 16 17 18 19 20 21]
  [22 23 24 25 26 29 28]]]


In [ ]:
# Change whole Inner Matrix To New Matrix 
c[1,:,:] = [[22,23,24,25,26,27,28],[29,30,31,32,33,34,35]]
print(c)

[[[ 1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14]]

 [[22 23 24 25 26 27 28]
  [29 30 31 32 33 34 35]]]


But Remember Changing Elements Or Array To A Different Size Or Dimensions Result In Error 

In [103]:
c[1,:,:] = [[4,5,6],[9,0,7]]

ValueError: could not broadcast input array from shape (2,3) into shape (2,7)

____________________________________________________________________________________________________________________________