# ***Numpy Tutorial***

# **Day1 Numpy Notes**

In [2]:
import numpy as np

#### **Array Initialization**

In [3]:
# Creates Array Of [3,6,8,53,7,3] using np.array() function

a = np.array([3,6,8,53,7,3])
print(a)

[ 3  6  8 53  7  3]


*You Can Also Create two or higher Dimensional Array Using Nested List*

In [4]:
# Creates Array With Two Dimension Using Nesting of List along with .array() function

b = np.array([[7,5,3,6],[35,8,4,2]])
print(b)

[[ 7  5  3  6]
 [35  8  4  2]]


In [5]:
# Different Data Types Can Also Be Used To Make Array In Numpy Python Library

c = np.array([[7.94,6,3,7.82,2.63],[9,37,8,3,8]])
print(c)

[[ 7.94  6.    3.    7.82  2.63]
 [ 9.   37.    8.    3.    8.  ]]


#### **Dimension Of Array**

*Number Of Dimension Of Arrays using ndim attribute*

In [6]:
# Finding Dimension Of Given Array by using .ndim() attribute
a.ndim

1

In [7]:
# Array With A Matrix Is Know As 2-Dimensional Or 2D
b.ndim

2

____________________________________________________________________________________________________________________________

#### **Shape Of Array**

*.shape attribute gives shape/no of element in each dimenstion of a given array in form of tuple of non-negative integers*


In [8]:
a.shape # Shape Of 'a' Array(here 'a' is a List with one dim of size 6)

(6,)

In [9]:
b.shape # Shape Of 'b' Array(here 'b' is Matrix of size 2x4)

(2, 4)

*Here Matrix B is a 2x4 matrrix so when we try to find shape of matrix or array it gives (2,4)*

***Whenever we check shape of array it is always stored in tuple***

____________________________________________________________________________________________________________________________

### **Data Type Of Array's Element**

*We Can Use .dtype attribute to find data type of given array*

*Actually Here Data Type Means data type and memory space allocated for it.*

*Arrays are homogenous means that they contains element of only one single data type*

In [10]:
# Data Type and Space Allocated For Every Element Of 'a' matrix 
a.dtype

dtype('int32')

*In Above Example dtype('int32') specifies datatype which is int and memory per element is 32*

In [11]:
# For 'b'
b.dtype

dtype('int32')

In [12]:
# For 'c'
c.dtype

dtype('float64')

*In Above Example Datatype here is float which is allocated 64 bit per element*

In [57]:
# You Can Also Change Data Type If Possible 
# While Creating Array 
a = np.array([8,9,6] , dtype = 'int16') 
# Helps To Manage Memory Effectively
print(a)
a.dtype

[8 9 6]


dtype('int16')

____________________________________________________________________________________________________________________________

### **ItemSize Of Element Of Array**

***Item Size Is Size/Memory Allocated For Element In Given Array In Bytes***

In [ ]:
# Depends On dtype of array
print(a.dtype)
a.itemsize

int32


4

*Here int32 means the data type is int and the memory allocated for each element is 32 bits, which is equal to 4 bytes*

In [15]:
b.itemsize

4

In [16]:
c.itemsize

8

*c array has elements of type float64 which means they have 64 bit of memory allocated for each element, which is equal to 8 bytes, thus the output shows 8 when we use .itemsize on array c*

*As Float Takes double The memory than int so ,it prints 8 (double the memory of int)*

____________________________________________________________________________________________________________________________

#### **Size / ItemSize**

*.size attribute gives total no of element in array*

In [17]:
a.size # Size Of Array 'a' using .size attribute

6

In [18]:
b.size # Size Of Array 'b' using .size attribute

8

In [19]:
c.size # Size Of Array 'c' using .size attribute

10

____________________________________________________________________________________________________________________________


#### **Total Size Of Array**

*Total Memory Size it can be calculated using .nbytes or simple maths calculation like  a.size * a.itemsize*

*Remember .nbytes gives size of array' total memory in bytes not bits*

In [20]:
# Total Memory Required For Whole Array 'a'

a.nbytes

24

In [21]:
# Same As Above But In Mathematical Terms

a.size * a.itemsize 

# a.size -> no of elements in array
# a.itemsize -> allocated memory size per element

24

In [22]:
# Total Memory Required For Whole Array 'b'

b.nbytes

32

In [23]:
c.nbytes # Total Size of array 'c' to get storage in memory in bytes

80

### **Accessing/Changing Specific Elements,rows,columns in Array**

In [24]:
a = np.array([[1,3,5,7,4,3,8],[0,7,5,3,7,4,2]])

In [25]:
# Get Specific Element 
# You Can Access Specific Element in Array By Using Indexing Same As In Python List

print(a[1,6])

2


In [26]:
# Get Specific Row 
a[1,:]

array([0, 7, 5, 3, 7, 4, 2])

In [27]:
# Get Specific Column
a[:,3]

array([7, 3])

In [28]:
# Get Complex Output 
# By Using List Slicing [start_index:end_index:step]

In [29]:
# Let We Want Element From 2 to 5 of second column

a[1,2:6:1]

array([5, 3, 7, 4])

*We have seen we can use slicing in numpy array just as list in python ,so we can use general form of slicing as np.array[start_point:end_point:steps]*

In [30]:
# Some Of Slicing Practice

a[0,1:-2:2]

array([3, 7])

In [31]:
a[0,2:6:2]

array([5, 4])

In [32]:
a[0,1:-1:2]

array([3, 7, 3])

In [33]:
# Changing Array Element
a[1,3] = 78

*Changing Whole Column/Row Element To One Common Element Or Iterate From List/Array*

In [34]:
a[0,:]=2
print(a)

[[ 2  2  2  2  2  2  2]
 [ 0  7  5 78  7  4  2]]


In [35]:
a[0,:]=[1,2,3,4,5,6,7]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 0  7  5 78  7  4  2]]


Accessing Element In 3D Array Is Done By Working Outside In Way

In [36]:
c = np.array([[[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]],[[15,16,17,18,19,20,21],[22,23,24,25,26,27,28]]])
print(c)

[[[ 1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14]]

 [[15 16 17 18 19 20 21]
  [22 23 24 25 26 27 28]]]


In [37]:
# Let's Access 9 From 3D Array

c[0,1,1]

9

If You Want To Change Element You Can Use Same Array Operation To Change Elements In Array

You Can Also Change Whole Matrix     

Just Access The Matrix You Want To Change And Add New Matrix

In [38]:
# Let's Change 24 to 29

c[1,1,5] = 29

In [39]:
print(c)

[[[ 1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14]]

 [[15 16 17 18 19 20 21]
  [22 23 24 25 26 29 28]]]


In [40]:
# Change whole Inner Matrix To New Matrix 
c[1,:,:] = [[22,23,24,25,26,27,28],[29,30,31,32,33,34,35]]
print(c)

[[[ 1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14]]

 [[22 23 24 25 26 27 28]
  [29 30 31 32 33 34 35]]]


But Remember Changing Elements Or Array To A Different Size Or Dimensions Result In Error 

In [41]:
c[1,:,:] = [[4,5,6],[9,0,7]]

ValueError: could not broadcast input array from shape (2,3) into shape (2,7)

____________________________________________________________________________________________________________________________

## **Initializing Different Types Of Arrays**

#### **Creating Arrays Filled Of Zeros**

*You can easily create array filled with zero*

*.zeros() function take argument as int or tuple to specify shape and dimension of array of zeros, you can specify dtype of it*

In [ ]:
np.zeros(4) # Array Of Zeros Created With 1 dimension of shape (4,)

array([0., 0., 0., 0.])

In [ ]:
np.zeros((5,6)) # Arrays Of Zeros Created with 2 dimension of shape (5,6)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((2,4,5)) # Arrays Of Zeros Created with 3 dimension of shape (2,4,5)

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
np.zeros((6,7,5,1,3)) # Arrays Of Zeros Created with n-dimension (here 5) of shape (6,7,5,1,3)

array([[[[[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]]],


        [[[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]]],


        [[[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]]],


        [[[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]]],


        [[[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]]],


        [[[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]]],


        [[[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]]]],



       [[[[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]

*We Can Also Create Array Of Zeros Using Shape of exgisting Array using .zeros_like() function*

In [ ]:
np.zeros_like(c)

array([[[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]]])

#### **Creating Arrays Filled Of Ones**

*You can create array filled with ones* 

*.ones() function takes same argument as int or tuple to specify shape and dimension of array*

In [ ]:
# All 1's Matrix
np.ones((8,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.ones((7,8,5,4),dtype = 'int16') # Ones Array Is Created With Shape Of (7,8,5,4) with specified datatype ('int16)

array([[[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        ...,

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]],


       [[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
  

*We Can Also Create Array Of Ones Using Shape of exgisting Array using .ones_like() function*

In [ ]:
np.ones_like(c) # Creating Array Of Ones Using existing array shape

array([[[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]]])

#### **Creating Arrays Filled Of Any Number**

*.full()i function takes two argument primarily one is shape and dimension , another is for element you want to fill in it*

In [ ]:
# All Xs Matrix
X = 3
np.full((3,4),X)
# Again Here You Can Change dtype of matrix 

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

*We Can Also Create Array of any number Using Shape of existing Array using .full_like() function*

In [ ]:
np.full_like(a,2) # Creating Array Of Given Number Of Size Of Some Existing Array

array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

In [ ]:
np.full(a.shape,2) # You Can Also Use a.shape as shape for defining shape of array of any number in .full() function

array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

### **Creating Array Of Random Number**

*Random Is A Class In Numpy which has multiple function , in which rand comes*

##### **Creating Array Of Random Number**

*.random.rand() function gives array with random number with specific shape*

.random.rand() function takes integers as length of dimension 

In [ ]:
np.random.rand(4,2) # Array of random number between (0,1) 

array([[0.80940216, 0.522087  ],
       [0.38223928, 0.62348563],
       [0.87704943, 0.18013628],
       [0.58886688, 0.87979868]])

##### **Creating Array Using Shape Of Exisiting Array**

*.random.random_sample() function is used to make a array of random number of shape of existing array*

In [ ]:
np.random.random_sample(a.shape) # Creating Array with random number using shape of an existing array

array([[0.69653117, 0.17520167, 0.29345178, 0.37856744, 0.83358136,
        0.44287918, 0.15176212],
       [0.04875083, 0.54859444, 0.60383255, 0.31724915, 0.18713658,
        0.06077441, 0.2223813 ]])

*.random.randint() function is used to create array of random integers*

In [ ]:
np.random.randint(4,9,size=(3)) # Creating Arrays Of Random Integers 

array([6, 5, 8])

##### **Initializing Identity Matrix Using .identiy() and .eye()**

*You can create identity matrix using .identity() function*

*.identity() function has only one argument which specifies length of both sides of sqaure identity matrix*

In [ ]:
#Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

*You Can Create Matrix Similar to identity but not a square matrix using .eye() function*

In [ ]:
np.eye(3,4,k=0) # Creating Array using .eye() function 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

##### **Syntax :-  np.eye(rows,column,k=[integers])**

**Here k is used to set position of diagonally placed 1's in matrix  negative number pulls element down and positive number pulls up**

In [ ]:
# Examples
np.eye(3,4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(3,4,k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [ ]:
np.eye(3,4,k=0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

#### **Repeat Function**

*.repeat() function is used repeat and exisiting or same arr to get a new array*

In [ ]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis = 0) # This Functio take three argument one for which array is used 
# second for how many times and third for on which axis should i move to print
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
# Practice Set Q1
arr1 = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
arr1[1:4,1:4] = z
print(arr1)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### **Python's Main Rule :- Every Thing Is Reference of Main Object**

In [ ]:
a = np.array([1,2,3])
b = a.copy()
print(b)
b[0] = 100
print(b)
print(a)

[1 2 3]
[100   2   3]
[1 2 3]


____________________________________________________________________________________________________________________________

## **Mathematics Using Numpy**

In [ ]:
a = np.array([1,2,3,4]) # Creating Array For Operation
print(a)

[1 2 3 4]


##### ***Addition On Numpy Array***

In [ ]:
# Addition 

a + 2

array([3, 4, 5, 6])

*Adding a scalar to a array result into adding that scalar to every element of array's element*

##### ***Subracting On Numpy Array***

In [ ]:
# Substraction 
# Same As Addition
a - 2

array([-1,  0,  1,  2])

##### ***Multiplication On Numpy Array***

In [ ]:
# Multiplication 
# Also Same

a*2

array([2, 4, 6, 8])

##### ***Division On Numpy Array***

In [ ]:
# Division
# Same As Above
a/2

array([0.5, 1. , 1.5, 2. ])

##### ***Concatinating Two Array Using '+' operator***

In [ ]:
# Additing Another Array To Original
print("a =",a)
b=np.array([1,0,1,0])
print("b =",b)
print("Concatinating Two Different Array of same shape")
print("a+b =",a+b)

a = [1 2 3 4]
b = [1 0 1 0]
Concatinating Two Different Array of same shape
a+b = [2 2 4 4]


***Remember:-Adding Arrays Works On Arrays with same shape otherwise it gives error***

In [ ]:
c = np.array([6,8,3])
a+c

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

*Addition Happens Between Two Element Of Array Of Same Index*

*Ex:- a = [6,7] b = [8,3]*<br>
*a+b = [6+8,7+3]*

##### ***Exponents Of Element Of Matrix***

In [ ]:
a ** 2 # '**' operator Is Used to find power of every element in an array

# 2 is power of array element which you required

array([ 1,  4,  9, 16])

##### ***Trigonametry On Element Of Matrix***

In [ ]:
# Trigonometrical Function
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


## **Linear Algebra**

***Matrix Multiplication Using In-Built Python Libraries***

In [ ]:
a = np.ones((2,3)) # Creating First Matrix
print(a)

b= np.full((3,2),2) # Creating Second Matrix
print(b)

np.matmul(a,b) # .matmul() function is used to multiply two matrices 

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

***Remember Matrix Multiplication has rules***<br>
* *in 2D Matrix No of rows of first matrix must equal to no fo column of second matrix if not it will throw an error*

In [ ]:
b = np.ones((8,5))

np.matmul(a,b)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 8 is different from 3)

In [ ]:
a = np.arange(24).reshape(2,3,4)
print(a)
b = np.arange(25,49).reshape(2,4,3)
print(b)

np.matmul(a,b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]

 [[37 38 39]
  [40 41 42]
  [43 44 45]
  [46 47 48]]]


array([[[ 192,  198,  204],
        [ 664,  686,  708],
        [1136, 1174, 1212]],

       [[2256, 2310, 2364],
        [2920, 2990, 3060],
        [3584, 3670, 3756]]])

In [ ]:
# Determinant of matrix

c = np.identity(3)
# I Have Used Identity Matrix To Check The Determinant Is 1 or not 
np.linalg.det(c)

1.0

## ***Statistics***
  

In [ ]:
stats = np.array([[1,2,3],[4,5,3]])
print(stats)

[[1 2 3]
 [4 5 3]]


***Mean(Average)***

In [ ]:
# Mean Of Data In NumPy
np.mean(stats) 

3.0

In [ ]:
# Max In Array
np.max(stats)

5

In [ ]:
# Min In Array
np.min(stats)

1

In [ ]:
# Sum Of All Element In Array
np.sum(stats)

18

In [ ]:
# We Can Use Different Function To Calculate Same Output But Numpy has its own function
print((np.sum(stats)/stats.size))

3.0


In [ ]:
# Introduction Of Axis In Picture
# In NumPy, `axis` defines **the direction in which an operation is applied**.
# 1D Array Only Has One Axis (Axis = 0)
# 2D Array Have 2 Axis (Axis = 0 for column-vice operation , Axis = 1 for row-vice operation)
'''row-vice axis tells the function to operate in row format means apply operation on elements which are traversed 
row vice ex axis = 0 for 2D Array'''
np.sum(stats,axis=1)

array([ 6, 12])

Axis Represents In Which Dimension Function Should Work 

For Example Above np.sum(stats,axis = 1) gives addition of element in columns-form

____________________________________________________________________________________________________________________________

# ***Day2 Numpy Notes***

### ***Reorganizing Arrays***

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(before.shape) # Shape Of Array Before reshaping

(2, 4)


***Convert array of shape (2,4) to (8,1)***<br>
***Be Careful Number Of Element Must Be Same*** <br>
***When Converting To Another Shape***<br>
***Or WhenEvery reshaping Check Product Of Dimension Of Shape if Both Number Are Equal or not ,if equal Then We Can reshape original*** <br>

In [ ]:
after = before.reshape(8,1) # Reshaping Array 'before to shape of (8,1)'
print(after)
print()
print(after.shape) # Shape Of New Array From array 'before' after reshaping

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]

(8, 1)


In [ ]:
after = before.reshape(2,2,2) # reshaping array to 3-dimensional array's shape
print(after)
print()
print(a.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

(2, 5)


***You Can Also Change Shape Of Array Using .shape() by changing output of shape method to required shape of new array***

In [ ]:
a = np.arange(10) 
print(a)
a.shape = (2,5) # Changing Shape Of Array Using .shape() function
print(a)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


##### ***Axis Explaination***

In [ ]:
a = np.array([[3,4,6,4],[6,3,1,5]])
b = np.array([[5,6,3,2],[5,6,3,2]])

a.sum(axis=1)

array([17, 15])

##### ***Vertical Stacking***

***Two Vectors/Array Are Stacked Using .vstack() with a tuple of two or more vectors as argument***

In [ ]:
# Vertically Stacking Vectors
v1 = np.array([[1,2],[3,4]])
v2 = np.array([[5,6],[7,8]])
v3 = np.array([[4,5],[2,7]])

np.vstack((v1,v2,v3)) # Stacking v1,v2,v3 on top of each other where first array's element are placed on top

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [4, 5],
       [2, 7]])

***Vertical Stacking Result A Array Where Element Of Previous Array Are Stacked on top of each other by following rule of first traversed will be on top***

***Arrays must have the same number of columns***<br>
***Think of it as stacking rows one under the another***

##### ***Horizontal Stacking***

***Same As Verical Stacking But Works In Horizontal Way***

***Here Stacking Happens Along Sideways<br>***
***One Can Imagine Two Arrays Placed Side By Side And Element On Same Index Are Merge Together And Placed On Same Position In New Array***

In [ ]:
# Horizontal Stack
h1 = np.array([[1,2],[3,4]])
h2 = np.array([[5,6],[7,8]])

np.hstack((h1,h2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

***Large Example For Understanding***

In [ ]:
v1 = np.random.randint(0, 10, size=(2, 3, 3, 3))
print(v1)
print()
v2 = np.random.randint(0,10,size=(2,3,3,3))
print(v2)

[[[[9 4 6]
   [3 3 2]
   [0 9 3]]

  [[3 5 7]
   [5 3 5]
   [6 1 6]]

  [[8 8 4]
   [8 9 0]
   [5 4 5]]]


 [[[3 3 0]
   [6 5 2]
   [5 6 3]]

  [[3 3 2]
   [8 3 8]
   [9 0 8]]

  [[5 3 4]
   [1 3 1]
   [9 5 9]]]]

[[[[3 0 2]
   [7 4 3]
   [4 8 1]]

  [[7 5 9]
   [4 8 0]
   [5 7 8]]

  [[3 7 9]
   [6 0 5]
   [1 4 1]]]


 [[[8 0 5]
   [2 9 7]
   [7 4 7]]

  [[2 3 4]
   [1 3 7]
   [5 6 0]]

  [[7 7 7]
   [9 4 7]
   [9 0 1]]]]


In [ ]:
np.vstack((v1,v2))

array([[[[9, 4, 6],
         [3, 3, 2],
         [0, 9, 3]],

        [[3, 5, 7],
         [5, 3, 5],
         [6, 1, 6]],

        [[8, 8, 4],
         [8, 9, 0],
         [5, 4, 5]]],


       [[[3, 3, 0],
         [6, 5, 2],
         [5, 6, 3]],

        [[3, 3, 2],
         [8, 3, 8],
         [9, 0, 8]],

        [[5, 3, 4],
         [1, 3, 1],
         [9, 5, 9]]],


       [[[3, 0, 2],
         [7, 4, 3],
         [4, 8, 1]],

        [[7, 5, 9],
         [4, 8, 0],
         [5, 7, 8]],

        [[3, 7, 9],
         [6, 0, 5],
         [1, 4, 1]]],


       [[[8, 0, 5],
         [2, 9, 7],
         [7, 4, 7]],

        [[2, 3, 4],
         [1, 3, 7],
         [5, 6, 0]],

        [[7, 7, 7],
         [9, 4, 7],
         [9, 0, 1]]]])

In [ ]:
np.hstack((v1,v2))

array([[[[9, 4, 6],
         [3, 3, 2],
         [0, 9, 3]],

        [[3, 5, 7],
         [5, 3, 5],
         [6, 1, 6]],

        [[8, 8, 4],
         [8, 9, 0],
         [5, 4, 5]],

        [[3, 0, 2],
         [7, 4, 3],
         [4, 8, 1]],

        [[7, 5, 9],
         [4, 8, 0],
         [5, 7, 8]],

        [[3, 7, 9],
         [6, 0, 5],
         [1, 4, 1]]],


       [[[3, 3, 0],
         [6, 5, 2],
         [5, 6, 3]],

        [[3, 3, 2],
         [8, 3, 8],
         [9, 0, 8]],

        [[5, 3, 4],
         [1, 3, 1],
         [9, 5, 9]],

        [[8, 0, 5],
         [2, 9, 7],
         [7, 4, 7]],

        [[2, 3, 4],
         [1, 3, 7],
         [5, 6, 0]],

        [[7, 7, 7],
         [9, 4, 7],
         [9, 0, 1]]]])

#### ***Spliting***

*There Are Two Major Function For Spliting Array np.split(array,section/tuple)*<br>
*.split() function takes first argument as array(given array) and second as 'Int' for dividing in section or 'tuple' for cutting and dividing across two points in tuple on array*

In [ ]:
array1 = np.array([[5,7,4,36],[7,4,2,6]])
np.split(array1,2)

[array([[ 5,  7,  4, 36]]), array([[7, 4, 2, 6]])]

In [ ]:
array1 = np.array([[5,7,4,36],[7,4,2,6]],dtype = 'int8')
np.split(array1,(1,4))

[array([[ 5,  7,  4, 36]], dtype=int8),
 array([[7, 4, 2, 6]], dtype=int8),
 array([], shape=(0, 4), dtype=int8)]

***Remember :- when spliting always divide in equal part or it will give an error***<br>
***for error free code use np.array_split() function same as split but handles extra element when divided uneqauly and also doesn't gives error***

#### ***Spliting Horizontally***

***using .hspilt(array,section) use can split array horizontally***

*This function has two arguments first is array and second is section it takes input as int or tuple*<br><br>
*Int For how much section do you want*<br><br>
*Tuple is for spliting array in three parts where tuple is worked as start and stop split makes one cut at start point(from tuple) in array aand at end point(from tuple) in array.Then it split array into three part one from array's start to tuple's start-1 second is from tuple's start to tuple's end-1 and third is from tuple's end to array's end*<br>


In [ ]:
array = np.array([[1,2,3,4],[6,7,8,9]])
print(array)

[[1 2 3 4]
 [6 7 8 9]]


# Miscellaneous

Load Data From File 

In [ ]:
import os
print(os.getcwd())

c:\Users\user\DS\NumPy


In [ ]:
with open("datafile.txt","r")as f :
    print(f.readlines())
    array = f

['42,21,19,29,12,89,48,59,24,34,56,39,4,14,98,86,78,31,73,84,99,58,98,24,\n', '31,32,66,36,82,70,4,16,71,62,90,12,2,18,6,22,12,47,0,33,52,91,99,54,\n', '29,43,75,27,60,71,73,22,4,67,29,23,88,6,55,4,4,73,0,39,96,49,72,79,\n', '13,22,14,99,7,18,69,16,4,98,32,89,27,75,15,53,67,65,48,84,8,2,14,32,\n', '32,46,75,12,86,75,6,63,97,31,94,58,13,23,52,35,3,64,40,95,31,1,30,58,\n', '5,4,13,41,75,38,73,44,82,31,3,40,13,58,62,70,15,60,74,13,34,42,93,84,\n', '38,55,62,87,10,43,0,30,90,51,55,1,54,12,62,30,51,74,69,86,78,51,57,55,\n']


In [ ]:
print(array)

<_io.TextIOWrapper name='datafile.txt' mode='r' encoding='utf-8'>


In [ ]:
data = np.genfromtxt('datafile.txt',delimiter = ',',dtype = 'int16')
data

array([[42, 21, 19, 29, 12, 89, 48, 59, 24, 34, 56, 39,  4, 14, 98, 86,
        78, 31, 73, 84, 99, 58, 98, 24],
       [31, 32, 66, 36, 82, 70,  4, 16, 71, 62, 90, 12,  2, 18,  6, 22,
        12, 47,  0, 33, 52, 91, 99, 54],
       [29, 43, 75, 27, 60, 71, 73, 22,  4, 67, 29, 23, 88,  6, 55,  4,
         4, 73,  0, 39, 96, 49, 72, 79],
       [13, 22, 14, 99,  7, 18, 69, 16,  4, 98, 32, 89, 27, 75, 15, 53,
        67, 65, 48, 84,  8,  2, 14, 32],
       [32, 46, 75, 12, 86, 75,  6, 63, 97, 31, 94, 58, 13, 23, 52, 35,
         3, 64, 40, 95, 31,  1, 30, 58],
       [ 5,  4, 13, 41, 75, 38, 73, 44, 82, 31,  3, 40, 13, 58, 62, 70,
        15, 60, 74, 13, 34, 42, 93, 84],
       [38, 55, 62, 87, 10, 43,  0, 30, 90, 51, 55,  1, 54, 12, 62, 30,
        51, 74, 69, 86, 78, 51, 57, 55]], dtype=int16)

In [ ]:
# Boolean Masking
# Advanced Indexing
data>50

array([[False, False, False, False, False,  True, False,  True, False,
        False,  True, False, False, False,  True,  True,  True, False,
         True,  True,  True,  True,  True, False],
       [False, False,  True, False,  True,  True, False, False,  True,
         True,  True, False, False, False, False, False, False, False,
        False, False,  True,  True,  True,  True],
       [False, False,  True, False,  True,  True,  True, False, False,
         True, False, False,  True, False,  True, False, False,  True,
        False, False,  True, False,  True,  True],
       [False, False, False,  True, False, False,  True, False, False,
         True, False,  True, False,  True, False,  True,  True,  True,
        False,  True, False, False, False, False],
       [False, False,  True, False,  True,  True, False,  True,  True,
        False,  True,  True, False, False,  True, False, False,  True,
        False,  True, False, False, False,  True],
       [False, False, False, False,

In [ ]:
data>=50

array([[False, False, False, False, False,  True, False,  True, False,
        False,  True, False, False, False,  True,  True,  True, False,
         True,  True,  True,  True,  True, False],
       [False, False,  True, False,  True,  True, False, False,  True,
         True,  True, False, False, False, False, False, False, False,
        False, False,  True,  True,  True,  True],
       [False, False,  True, False,  True,  True,  True, False, False,
         True, False, False,  True, False,  True, False, False,  True,
        False, False,  True, False,  True,  True],
       [False, False, False,  True, False, False,  True, False, False,
         True, False,  True, False,  True, False,  True,  True,  True,
        False,  True, False, False, False, False],
       [False, False,  True, False,  True,  True, False,  True,  True,
        False,  True,  True, False, False,  True, False, False,  True,
        False,  True, False, False, False,  True],
       [False, False, False, False,

In [ ]:
data[data>50] # This Gives Values Which Are Greater Than 50 or given value

array([89, 59, 56, 98, 86, 78, 73, 84, 99, 58, 98, 66, 82, 70, 71, 62, 90,
       52, 91, 99, 54, 75, 60, 71, 73, 67, 88, 55, 73, 96, 72, 79, 99, 69,
       98, 89, 75, 53, 67, 65, 84, 75, 86, 75, 63, 97, 94, 58, 52, 64, 95,
       58, 75, 73, 82, 58, 62, 70, 60, 74, 93, 84, 55, 62, 87, 90, 51, 55,
       54, 62, 51, 74, 69, 86, 78, 51, 57, 55], dtype=int16)

In [ ]:
# identify any value in this data 's columns is greater 80
np.any(data>80,axis=0)

array([False, False, False,  True,  True,  True, False, False,  True,
        True,  True,  True,  True, False,  True,  True, False, False,
       False,  True,  True,  True,  True,  True])

In [ ]:
# Here axis = 0 represent row-wise iteration and which every row has any element greater than 80 is stored as true other
# who are'nt are stored as false
# You Can Also Check That All Element are greater than 80 or not using

np.all(data>80,axis=0)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [ ]:
# Conditonal Indexing
(data>40) & (data<80)

array([[ True, False, False, False, False, False,  True,  True, False,
        False,  True, False, False, False, False, False,  True, False,
         True, False, False,  True, False, False],
       [False, False,  True, False, False,  True, False, False,  True,
         True, False, False, False, False, False, False, False,  True,
        False, False,  True, False, False,  True],
       [False,  True,  True, False,  True,  True,  True, False, False,
         True, False, False, False, False,  True, False, False,  True,
        False, False, False,  True,  True,  True],
       [False, False, False, False, False, False,  True, False, False,
        False, False, False, False,  True, False,  True,  True,  True,
         True, False, False, False, False, False],
       [False,  True,  True, False, False,  True, False,  True, False,
        False, False,  True, False, False,  True, False, False,  True,
        False, False, False, False, False,  True],
       [False, False, False,  True,

In [ ]:
# You Can Also Obtain Numbers which follows this condition bytearray
data[(data>40) & (data<80)]
# or
data[((data>40) & (data<80))]

array([42, 48, 59, 56, 78, 73, 58, 66, 70, 71, 62, 47, 52, 54, 43, 75, 60,
       71, 73, 67, 55, 73, 49, 72, 79, 69, 75, 53, 67, 65, 48, 46, 75, 75,
       63, 58, 52, 64, 58, 41, 75, 73, 44, 58, 62, 70, 60, 74, 42, 55, 62,
       43, 51, 55, 54, 62, 51, 74, 69, 78, 51, 57, 55], dtype=int16)

In [ ]:
# Using Not Operator '~'
(~((data>40) & (data<80)))

array([[False,  True,  True,  True,  True,  True, False, False,  True,
         True, False,  True,  True,  True,  True,  True, False,  True,
        False,  True,  True, False,  True,  True],
       [ True,  True, False,  True,  True, False,  True,  True, False,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True, False,  True,  True, False],
       [ True, False, False,  True, False, False, False,  True,  True,
        False,  True,  True,  True,  True, False,  True,  True, False,
         True,  True,  True, False, False, False],
       [ True,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True, False,  True, False, False, False,
        False,  True,  True,  True,  True,  True],
       [ True, False, False,  True,  True, False,  True, False,  True,
         True,  True, False,  True,  True, False,  True,  True, False,
         True,  True,  True,  True,  True, False],
       [ True,  True,  True, False,

*You Can Index with a list in Numpy*

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a[[1,2,6]]) 
# Here First Square Bracket (Outer) Is for accessing a's array and second one is for generating list of element of array 'a' 
# at given index

[2 3 7]


## ***Day4 Numpy Notes***

### ***Advanced Indexing***

**There Are Two Types Of Advanced Array Indexing**<br>
* *Integer Array Indexing*<br>
* *Boolean Array Indexing*

***Integer Array Indexing***

*Integer array indexing refers to selecting elements from an N-dimensional array using another array of integers, where each integer or set of integers specifies a position along a particular axis.*

For Example:-

In [43]:
x = np.arange(3,28).reshape(5,5)
print(x)
print(x[3,4])
x[np.array([3,4,1])]

[[ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]
 [18 19 20 21 22]
 [23 24 25 26 27]]
22


array([[18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27],
       [ 8,  9, 10, 11, 12]])

In [44]:
x=np.array([[1,2],[3,4],[5,6]])
x[np.array([1,2]),np.array([0])]

array([3, 5])

*Integer indexing in NumPy extends basic indexing by using arrays of integers to specify explicit positions across one or more dimensions. Each integer (or set of integers) is used in coordination with others to select specific elements. The result is a new array—a copy of the original data, not a view—constructed by iterating over these index combinations.*

*Remember If index value are out of bounds then is throws a IndexError*

*When performing indexing on an N-dimensional array using N separate integer arrays, NumPy treats each integer array as specifying indices along a particular axis. It then performs element-wise selection by combining the corresponding elements from each index array, extracting values from those coordinated positions.*

In [45]:
x = np.arange(0,100).reshape(10,10) # 2D Array
print(x)
x[np.array([1,2,5,8]),np.array([3,4,6,7])] # 2 Integer array used for indexing

# Array Used Here Are Interpreted as [r,c] where r and c which are looped across 2-2 values each
# Thats Why there are 4 output corresponding to each pair

# 1<->3 --> 13 , 2<->4 --> 24 , 5<->6 --> 56 , 8<->7 --> 87

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


array([13, 24, 56, 87])

*Lets Try To Pair Different Size Of Array With Each Other*

In [46]:
x[np.array([2,3,4]),np.array([5,6,7,8])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (4,) 

*This Gives A Shape Mismatched Error means broadcasting is not possible here*<br>

*Important Point :- When There N Integer Indexing Array for N Dimensional Array, then Resultant Output Is Same Size As Size of Indexing Array*

* *When Combining Integer Indexing Array with scalar broadcasting is used*

In [47]:
x[np.array([2,3]),0] # Accessing Element from array with one index is fix or one index is scalar

array([20, 30])

##### **Broadcasting(Short Introduction)**

***Broadcasting descibes how numpy treats arrays with different shaped during arithmatic operations***

*Smaller Array Are Broadcasted over larger array for there shape compatibilty*<br>
*Or It Stretches smaller array over larger ones*<br>
*Streching is a conceptual Numpy doesn't make copies of smaller array it uses original array efficently*

In [48]:
a = np.array([[6,7,8,3,7,5],[2,4,6,4]])
b = np.array([7,8,9])

a*b

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.