## ***Numpy Practice Set***

In [2]:
import numpy as np

#### Q1:-How To Make 1D Array from ranging 0 to 9

In [3]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Q2:-Create a 3×3 numpy array of all True’s

In [4]:
b = np.ones((3,3),dtype = 'bool')
b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#### Q3:-Extract all odd numbers from arr <br>

#### arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

#### Q4:-Replace all odd numbers in arr with -1

In [6]:
arr = np.arange(0,10)
newarr = np.copy(arr)

newarr[newarr%2 == 1] = -1
print("Original:-",arr)
print("New Array:-",newarr)

Original:- [0 1 2 3 4 5 6 7 8 9]
New Array:- [ 0 -1  2 -1  4 -1  6 -1  8 -1]


Q5:-Convert a 1D array to a 2D array with 2 rows

In [7]:
np.arange(10).reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Q6:-Stack arrays a and b vertically<br>
a = np.arange(10).reshape(2,-1)<br>
b = np.repeat(1, 10).reshape(2,-1)


In [8]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Q7:- Stack arrays a and b horizontally

In [9]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

Q8:-Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

In [10]:
a = np.array([1,2,3])
r1 = np.repeat(a,3,axis = 0)
print(r1)
r2 = np.tile(a,3)
r2

np.hstack((r1,r2))

[1 1 1 2 2 2 3 3 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Q9:-Get the common items between a and b

In [11]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

Q11:-How to remove element from one array those exist in another

In [12]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.setdiff1d(a,b)

array([1, 3, 5, 6])

Q12:-How to get the position where elements of two arrays match

In [13]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

Q13:- How to extract all numbers between a given range from a numpy array ?

In [14]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>=5) & (a<=10)]

array([ 6,  9, 10])

Q14:-How to make a python function that handles scalars to work on numpy arrays ?

In [15]:
def maxx(a,b):
    return np.maximum(a,b)


a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
maxx(a,b)

array([6, 7, 9, 8, 9, 7, 5])

Q15:-How to swap two columns in a 2d numpy array?

In [16]:
arr = np.arange(9).reshape(3,3)
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

Q16:-How to swap two rows in a 2d numpy array?

In [17]:
arr = np.arange(9).reshape(3,3)
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

Q17:-How to reverse the rows of a 2D array?

In [18]:
arr = np.arange(9).reshape(3,3)
arr[::-1,:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

Q18:-How to reverse the columns of a 2D array?

In [19]:
arr = np.arange(9).reshape(3,3)
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])


Q19:-How to create a 2D array containing random floats between 5 and 10?

In [20]:
arr = np.random.uniform(5,10,size=(5,3))
arr

array([[7.25795905, 8.74972882, 5.57872553],
       [6.40076453, 6.7621149 , 7.513098  ],
       [5.84284393, 7.73643459, 6.15710318],
       [5.15494647, 5.4756369 , 6.75895525],
       [5.07258939, 6.21464907, 5.9187033 ]])

Q20:-How to print only 3 decimal places in python numpy array?

In [21]:
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=4)
rand_arr

array([[0.1794, 0.1817, 0.0751],
       [0.4604, 0.8687, 0.0202],
       [0.6429, 0.3041, 0.5278],
       [0.913 , 0.8001, 0.2909],
       [0.967 , 0.7646, 0.512 ]])

Q21:-How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

In [22]:
np.random.seed(100)
randomarr = np.random.random([3,3])/1e3
randomarr

array([[5.4340e-04, 2.7837e-04, 4.2452e-04],
       [8.4478e-04, 4.7189e-06, 1.2157e-04],
       [6.7075e-04, 8.2585e-04, 1.3671e-04]])

Q22:-How to limit the number of items printed in output of numpy array?



In [23]:
a = np.arange(15)
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

Q23:-How to print the full numpy array without truncating

In [24]:
np.set_printoptions(threshold=15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Q24:-How to import a dataset with numbers and texts keeping the text intact in python numpy?

In [25]:
iris_data = np.genfromtxt('Iris.csv', delimiter=',',dtype=object)
iris_data

array([[b'Id', b'SepalLengthCm', b'SepalWidthCm', b'PetalLengthCm',
        b'PetalWidthCm', b'Species'],
       [b'1', b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'2', b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       ...,
       [b'148', b'6.5', b'3.0', b'5.2', b'2.0', b'Iris-virginica'],
       [b'149', b'6.2', b'3.4', b'5.4', b'2.3', b'Iris-virginica'],
       [b'150', b'5.9', b'3.0', b'5.1', b'1.8', b'Iris-virginica']],
      dtype=object)

Q25:-How to extract a particular column from 1D array of tuples?

In [29]:
iris_data[:,-1]

array([b'Species', b'Iris-setosa', b'Iris-setosa', ..., b'Iris-virginica',
       b'Iris-virginica', b'Iris-virginica'], dtype=object)

Q26:-How to convert a 1d array of tuples to a 2d numpy array?

TypeError: Cannot change data-type for object array.