# ***Numpy Tutorial***

***Note Down***<br>
*when using attribute use it with array.atrribute*<br>
*For Example let a is array of numbers*<br>
*attributes are used as a.attribute*<br><br>
*when using function use it with np.function()*<br>
*For Example let a and b be two array of numbers*<br>
*function are used as np.add(a,b)*

# **Day1 Numpy Notes**

In [84]:
import numpy as np # importing numpy library to python environment

#### **Array Initialization**

*Creating Array Using np.array() function*

In [43]:
# Creates Array Of [3,6,8,53,7,3] using np.array() function

a = np.array([3,6,8,53,7,3])
print(a)

[ 3  6  8 53  7  3]


* *np.array() function uses only one argument which can be a list or tuple*

*You Can Also Create two or higher Dimensional Array Using Nested List*

In [44]:
# Creates Array With Two Dimension Using Nesting of List along with .array() function

b = np.array([[7,5,3,6],[35,8,4,2]])
print(b)

[[ 7  5  3  6]
 [35  8  4  2]]


In [45]:
# Different Data Types Can Also Be Used To Make Array In Numpy Python Library

c = np.array([[7.94,6,3,7.82,2.63],[9,37,8,3,8]])
print(c)

[[ 7.94  6.    3.    7.82  2.63]
 [ 9.   37.    8.    3.    8.  ]]


#### **Dimension Of Array**

*Number Of Dimension Of Arrays using ndim attribute*

In [46]:
# Finding Dimension Of Given Array by using .ndim() attribute
a.ndim

1

In [47]:
# Array With A Matrix Is Know As 2-Dimensional Or 2D
b.ndim

2

___________________________________________________________________________________________________________________________________________________

#### **Shape Of Array**

*.shape attribute gives no of element in each dimenstion of a given array in form of tuple of non-negative integers*


In [48]:
a.shape # Shape Of 'a' Array(here 'a' is a List with one dim of size 6)

(6,)

In [49]:
b.shape # Shape Of 'b' Array(here 'b' is Matrix of size 2x4)

(2, 4)

*Here Matrix B is a 2x4 matrrix so when we try to find shape of matrix or array it gives (2,4)*

***Whenever we check shape of array it is always stored in tuple***

____________________________________________________________________________________________________________________________

### **Data Type Of Array's Element**

*We Can Use .dtype attribute to find data type of given array*

*Actually Here Data Type Means data type and memory space allocated for it.*

*Arrays are homogenous means that they contains element of only one single data type*

In [50]:
# Data Type and Space Allocated For Every Element Of 'a' matrix 
a.dtype

dtype('int32')

*In Above Example dtype('int32') specifies datatype which is int and memory per element is 32*

In [51]:
# For 'b'
b.dtype

dtype('int32')

In [52]:
# For 'c'
c.dtype

dtype('float64')

*In Above Example Datatype here is float which is allocated 64 bit per element*

In [53]:
# You Can Also Change Data Type If Possible 
# While Creating Array 
a = np.array([8,9,6] , dtype = 'int16') 
# Helps To Manage Memory Effectively
print(a)
a.dtype

[8 9 6]


dtype('int16')

____________________________________________________________________________________________________________________________

### **ItemSize Of Element Of Array**

***Item Size Is Size/Memory Allocated For Element In Given Array In Bytes***

In [54]:
# Depends On dtype of array
print(a.dtype)
print(a.itemsize)

int16
2


In [55]:
b.dtype

dtype('int32')

*Here int32 means the data type is int and the memory allocated for each element is 32 bits, which is equal to 4 bytes*

In [56]:
b.itemsize

4

In [57]:
c.itemsize

8

*c array has elements of type float64 which means they have 64 bit of memory allocated for each element, which is equal to 8 bytes, thus the output shows 8 when we use .itemsize on array c*

____________________________________________________________________________________________________________________________

#### **Size / ItemSize**

*.size attribute gives total no of element in array*

In [58]:
a.size # Size Of Array 'a' using .size attribute

3

In [59]:
b.size # Size Of Array 'b' using .size attribute

8

In [60]:
c.size # Size Of Array 'c' using .size attribute

10

____________________________________________________________________________________________________________________________


#### **Total Size Of Array**

*Total Memory Size it can be calculated using .nbytes or simple maths calculation like  a.size * a.itemsize*

*Remember .nbytes gives size of array' total memory in bytes not bits*

In [61]:
# Total Memory Required For Whole Array 'a'

a.nbytes

6

In [62]:
# Same As Above But In Mathematical Terms

a.size * a.itemsize 

# a.size -> no of elements in array
# a.itemsize -> allocated memory size per element

6

In [63]:
# Total Memory Required For Whole Array 'b'

b.nbytes

32

In [64]:
c.nbytes # Total Size of array 'c' to get storage in memory in bytes

80

___________________________________________________________________________________________________________________________________________________

### **Accessing/Changing Specific Elements,rows,columns in Array**

In [65]:
a = np.array([[1,3,5,7,4,3,8],[0,7,5,3,7,4,2]])

In [66]:
# Get Specific Element 
# You Can Access Specific Element in Array By Using Indexing Same As In Python List
print(a[1,6])

2


In [67]:
# Get Specific Row from array by slicing
a[1,:]

array([0, 7, 5, 3, 7, 4, 2])

In [68]:
# Get Specific Column from array by slicing
a[:,3]

array([7, 3])

In [69]:
# Get Complex Output 
# By Using List Slicing [start_index:end_index:step]

In [70]:
# Let We Want Element From 2 to 5 of second column

a[1,2:6:1] # First 1 before ',' is used to iterate on second row and slicing after ',' is used to get element from 2 to 5 in same row

array([5, 3, 7, 4])

*We have seen we can use slicing in numpy array just as list in python ,so we can use general form of slicing as <br> 
np.array[start_point : end_point : steps]*

In [71]:
# Slicing Practice
# Get Element From First Row Of Array and from second to second last element in steps of twos
a[0,1:-2:2] 

array([3, 7])

In [72]:
# Get Element From First Row Of Array And From thrid to last element in steps of twos
a[0,2:6:2]

array([5, 4])

In [73]:
# Get Element From First Row Of Array And From Seconf Element To Last in steps of twos
a[0,1:-1:2]

array([3, 7, 3])

#### **Changing Array Element**

In [74]:

a[1,3] = 78

*Changing Whole Column/Row Element To One Common Element Or Iterate From List/Array*

In [75]:
a[0,:]=2
print(a)

[[ 2  2  2  2  2  2  2]
 [ 0  7  5 78  7  4  2]]


In [76]:
a[0,:]=[1,2,3,4,5,6,7]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 0  7  5 78  7  4  2]]


Accessing Element In 3D Array Is Done By Working Outside In Way

In [77]:
c = np.array([[[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]],[[15,16,17,18,19,20,21],[22,23,24,25,26,27,28]]])
print(c)

[[[ 1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14]]

 [[15 16 17 18 19 20 21]
  [22 23 24 25 26 27 28]]]


In [78]:
# Let's Access 9 From 3D Array

c[0,1,1]

9

If You Want To Change Element You Can Use Same Array Operation To Change Elements In Array

You Can Also Change Whole Matrix     

Just Access The Matrix You Want To Change And Add New Matrix

In [79]:
# Let's Change 24 to 29

c[1,1,5] = 29

In [80]:
print(c)

[[[ 1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14]]

 [[15 16 17 18 19 20 21]
  [22 23 24 25 26 29 28]]]


In [81]:
# Change whole Inner Matrix To New Matrix 
c[1,:,:] = [[22,23,24,25,26,27,28],[29,30,31,32,33,34,35]]
print(c)

[[[ 1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14]]

 [[22 23 24 25 26 27 28]
  [29 30 31 32 33 34 35]]]


But Remember Changing Elements Or Array To A Different Size Or Dimensions Result In Error 

In [82]:
c[1,:,:] = [[4,5,6],[9,0,7]]

ValueError: could not broadcast input array from shape (2,3) into shape (2,7)

____________________________________________________________________________________________________________________________

## **Initializing Different Types Of Arrays**

#### **Creating Arrays Filled Of Zeros**

*You can easily create array filled with zero*

*.zeros() function take argument as int or tuple to specify shape and dimension of array of zeros, you can specify dtype of it*

In [ ]:
np.zeros(4) # Array Of Zeros Created With 1 dimension of shape (4,)

array([0., 0., 0., 0.])

In [ ]:
np.zeros((5,6)) # Arrays Of Zeros Created with 2 dimension of shape (5,6)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((2,4,5)) # Arrays Of Zeros Created with 3 dimension of shape (2,4,5)

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
np.zeros((6,7,5,1,3)) # Arrays Of Zeros Created with n-dimension (here 5) of shape (6,7,5,1,3)

array([[[[[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]]],


        [[[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]]],


        [[[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]]],


        [[[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]]],


        [[[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]]],


        [[[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]]],


        [[[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]]]],



       [[[[0., 0., 0.]],

         [[0., 0., 0.]],

         [[0., 0., 0.]

*We Can Also Create Array Of Zeros Using Shape of exgisting Array using .zeros_like() function*

In [ ]:
np.zeros_like(c)

array([[[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]]])

___________________________________________________________________________________________________________________________________________________

#### **Creating Arrays Filled Of Ones**

*You can create array filled with ones* 

*.ones() function takes same argument as int or tuple to specify shape and dimension of array*

In [ ]:
# All 1's Matrix
np.ones((8,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.ones((7,8,5,4),dtype = 'int16') # Ones Array Is Created With Shape Of (7,8,5,4) with specified datatype ('int16)

array([[[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        ...,

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]],


       [[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
  

*We Can Also Create Array Of Ones Using Shape of exgisting Array using .ones_like() function*

In [ ]:
np.ones_like(c) # Creating Array Of Ones Using shape of existing array

array([[[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]]])

___________________________________________________________________________________________________________________________________________________

#### **Creating Arrays Filled Of Any Number**

*.full() function takes two argument primarily one is shape and dimension , another is for element you want to fill in it*

In [ ]:
# All Xs Matrix
X = 3
np.full((3,4),X)
# Again Here You Can Change dtype of matrix 

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

*We Can Also Create Array of any number Using Shape of existing Array using .full_like() function*

In [ ]:
np.full_like(a,2) # Creating Array Of Given Number Of Size Of Some Existing Array

array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

In [ ]:
np.full(a.shape,2) # You Can Also Use a.shape as shape for defining shape of array of any number in .full() function

array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

___________________________________________________________________________________________________________________________________________________

### **Creating Array Of Random Number**

*Random Is A Class In Numpy which has multiple function , in which rand comes*

*.random.rand() function gives array with random number with specific shape*

.random.rand() function takes integers as length of dimension 

In [ ]:
np.random.rand(4,2) # Array of random number between (0,1) 

array([[0.28036439, 0.02016625],
       [0.60362524, 0.60840867],
       [0.02630436, 0.41398317],
       [0.28741108, 0.26848553]])

np.random.rand() function always generate numbers between 0,1 

##### **Creating Array Using Shape Of Exisiting Array**

*.random.random_sample() function is used to make a array of random number of shape of existing array*

In [ ]:
np.random.random_sample(a.shape) # Creating Array with random number using shape of an existing array

array([[0.22060663, 0.61859513, 0.33787663, 0.1774333 , 0.15274366,
        0.3227406 , 0.32575366],
       [0.47988897, 0.89831355, 0.99477931, 0.43747586, 0.75030528,
        0.56231408, 0.72268226]])

*.random.randint() function is used to create array of random integers*

*Syntax:-*<br>
*np.random.randint(start_point,end_point,size=(shape))*

*Here start_point and endpoint will guild function to generate value in between this two points and size defines shape of random array*

In [ ]:
np.random.randint(4,9, size = (4,5)) # Creating Arrays Of Random Integers 

array([[8, 6, 4, 6, 5],
       [4, 8, 6, 7, 8],
       [7, 4, 4, 5, 5],
       [6, 4, 4, 8, 5]])

___________________________________________________________________________________________________________________________________________________

##### **Initializing Identity Matrix Using .identity() and .eye()**

*You can create identity matrix using .identity() function*

*.identity() function has only one argument which specifies length of both sides of sqaure identity matrix*

In [ ]:
#Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

*You Can Create Matrix Similar to identity but not a square matrix using .eye() function*

In [ ]:
np.eye(3,4,k=0) # Creating Array using .eye() function 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

##### **Syntax :-  np.eye(rows,column,k=[integers])**

**Here k is used to set position of diagonally placed 1's in matrix , negative value of k tends to pulls element down and positive value pulls up**

In [ ]:
# Examples
np.eye(3,4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(3,4,k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [ ]:
np.eye(3,4,k=0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

___________________________________________________________________________________________________________________________________________________

#### **Repeat Function**

*.repeat() function is used repeat an existing or same array to get a new array*

***Note:-repeat() function repeats all the element of array along specified axis***

In [ ]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis = 0) # This Function take three argument one for which array is used 
# second for how many times and third for on which axis should i move to print
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
arr = np.array([[2,3,4]])
r2 = np.repeat(arr,5,axis=1) # this function duplicate every element of arr and print by repeating one element at a time then next
print(r2)

[[2 2 2 2 2 3 3 3 3 3 4 4 4 4 4]]


#### **Tile Function**

Construct an Array by repeacting original array by number of times using .tile() function 

it has two argument one is array which will get repeated and another is how many times it will repeat

In [ ]:
a = np.arange(10)
a
np.tile(a,4)  # Generates New Array By Using Old Array As Placed In one row


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
       2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Note:- .repeat() and .tile() are different in terms of element and whole array repeatition<br>
         .repeat() allows to repeat elements of array where it traverse every element of array<br>
         .tile() allows to repeat whole array where it only repeat and print original whole array with changing array elements**

____________________________________________________________________________________________________________________________

## **Mathematics Using Numpy**

In [ ]:
a = np.array([1,2,3,4]) # Creating Array For Operation
print(a)

[1 2 3 4]


##### ***Addition On Numpy Array***

In [ ]:
# Addition using + operator
# Array + Scalar
a + 2 # Only View no change in original array

array([3, 4, 5, 6])

*Adding a scalar to a array result into adding that scalar to every element of array's element*

In [ ]:
# Array + Array
print("a =",a)
b=np.array([1,0,1,0])
print("b =",b)
print("Concatinating Two Different Array of same shape")
print("a+b =",a+b) # New Array Is Created

a = [1 2 3 4]
b = [1 0 1 0]
Concatinating Two Different Array of same shape
a+b = [2 2 4 4]


*Addition two array using + result into adding element of first array to element of corresponding index in second array*

In [ ]:
# Addition using np.add() function
np.add(a,4)

array([5, 6, 7, 8])

In [ ]:
np.add(a,a) 

array([2, 4, 6, 8])

*np.add() function requires two argument ,they can be two array , two integers , one array one integer*

##### ***Subracting On Numpy Array***

In [ ]:
# Substraction using - operator
# Array + Scalar
# Same As Addition

a - 2

array([-1,  0,  1,  2])

In [ ]:
# Array + Array
print("a=",a)
print("b=",b)
print(a-b)

a= [1 2 3 4]
b= [1 0 1 0]
[0 2 2 4]


In [ ]:
# Substraction using np.subtract()
np.subtract(a,2)
# Same As Substraction

array([-1,  0,  1,  2])

##### ***Multiplication On Numpy Array***

In [ ]:
# Multiplication using * operator
# Also Same

a*2

array([2, 4, 6, 8])

##### ***Division On Numpy Array***

In [ ]:
# Division
# Same As Above
a/2

array([0.5, 1. , 1.5, 2. ])

##### ***Concatinating Two Array Using '+' operator***

In [ ]:
# Additing Another Array To Original
print("a =",a)
b=np.array([1,0,1,0])
print("b =",b)
print("Concatinating Two Different Array of same shape")
print("a+b =",a+b)

a = [1 2 3 4]
b = [1 0 1 0]
Concatinating Two Different Array of same shape
a+b = [2 2 4 4]


***Remember:-Adding Arrays Works On Arrays with same shape otherwise it gives error***

In [ ]:
c = np.array([6,8,3])
a+c

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

*Addition Happens Between Two Element Of Array Of Same Index*

*Ex:- a = [6,7] b = [8,3]*<br>
*a+b = [6+8,7+3]*

##### ***Exponents Of Element Of Matrix***

In [ ]:
a ** 2 # '**' operator Is Used to find power of every element in an array


array([ 1,  4,  9, 16])

In [ ]:
a**b

array([1, 1, 3, 1])

*When calculating exponent of a over b it works by finding exponent of every element of a to power of b's element*

Ex:- a = [3,4] b = [2,3]<br>
a ** b = [3 ** 2 , 4 ** 3]<br>

***Remember:- Taking exponent Of Two Array Always Required to have arrays of same shape otherwise error will take place***

##### ***Trigonametry On Element Of Matrix***

In [ ]:
# Trigonometrical Function
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


___________________________________________________________________________________________________________________________________________________

## **Linear Algebra**

***Matrix Multiplication Using In-Built Python Libraries***

In [ ]:
a = np.ones((2,3)) # Creating First Matrix
print(a)

b= np.full((3,2),2) # Creating Second Matrix
print(b)

np.matmul(a,b) # .matmul() function is used to multiply two matrices 

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

***Remember Matrix Multiplication has rules***<br>
* *in 2D Matrix No of rows of first matrix must equal to no fo column of second matrix if not it will throw an error*

In [ ]:
b = np.ones((8,5))

np.matmul(a,b)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 8 is different from 3)

In [ ]:
a = np.arange(24).reshape(2,3,4)
print(a)
b = np.arange(25,49).reshape(2,4,3)
print(b)

np.matmul(a,b)

In [ ]:
# Determinant of matrix

c = np.identity(3)
# I Have Used Identity Matrix To Check The Determinant Is 1 or not 
np.linalg.det(c)

1.0

___________________________________________________________________________________________________________________________________________________

## ***Statistics***
  

In [ ]:
stats = np.array([[1,2,3],[4,5,3]])
print(stats)

[[1 2 3]
 [4 5 3]]


***Mean(Average)***

In [ ]:
# Mean Of Data In NumPy
np.mean(stats) 

3.0

***Element With Maximum Value in Array***<br>
*using np.max() function*

In [ ]:
# Max In Array
np.max(stats)

5

***Element With Minimum Value in Array***<br>
*using np.min() function*

In [ ]:
# Min In Array
np.min(stats)

1

***Sum Of All Element In Array***

In [ ]:
# Sum Of All Element In Array
np.sum(stats)

18

In [ ]:
# We Can Use Different Function To Calculate Same Output But Numpy has its own function

print((np.sum(stats)/stats.size)) # Calculating Average/Mean

3.0


***Standard Deviation of all elements in array***

In [ ]:
np.std(stats)

1.2909944487358056

***Variance of all elements in array***

In [ ]:
np.var(stats)

1.6666666666666667

## ***Axis of array***

*In NumPy, axis defines the direction along which operations like sum, mean, max are applied in multi-dimensional arrays.*

*1D Array Only Has One Axis (Axis = 0)*<br>
*2D Array Have 2 Axis (Axis = 0 for column-wice operation , Axis = 1 for row-wice operation)*

In [ ]:
'''row-wice axis tells the function to operate in 
row format means apply operation on elements 
which are traversed row wice ex axis = 0 for 2D Array'''
print(stats)
np.sum(stats,axis=1)

[[1 2 3]
 [4 5 3]]


array([ 6, 12])

Axis Represents In Which Dimension Function Should Work 

For Example Above np.sum(stats,axis = 1) calculates sum of all element along row with additing all elements of single column <br>
[[9,4,5,3,5],<br>
 [6,3,2,6,3],<br>
 [0,2,3,5,2]]<br>


____________________________________________________________________________________________________________________________

# ***Day2 Numpy Notes***

### ***Reorganizing Arrays***

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(before.shape) # Shape Of Array Before reshaping

(2, 4)


***Convert array of shape (2,4) to (8,1)***<br>
***Be Careful Number Of Element Must Be Same.*** <br><br>
***Whenever reshaping Check Product Of Dimension Of Shape of previous and new shape , if Both Number Are Equal or not <br>,if equal then We Can reshape original if not then we should try broadcasting and broadcasting is also not possible <br> so we cannot reshape array into that shape*** <br>

In [ ]:
after = before.reshape(8,1) # Reshaping Array 'before to shape of (8,1)'
print(after)
print()
print(after.shape) # Shape Of New Array From array 'before' after reshaping

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]

(8, 1)


In [ ]:
after = before.reshape(2,2,2) # reshaping array to 3-dimensional array's shape
print(after)
print()
print(a.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

(2, 3)


***You Can Also Change Shape Of Array Using .shape() by changing output of shape method to required shape of new array***

In [ ]:
a = np.arange(10) 
print(a)
a.shape = (2,5) # Changing Shape Of Array Using .shape() function
print(a)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


_____________________________________________________________________________________________________________________________

### ***Vertical Stacking***

***Two Vectors/Array Are Stacked Using .vstack() with a tuple of two or more vectors as argument***

In [ ]:
# Vertically Stacking Vectors
v1 = np.array([[1,2],[3,4]])
v2 = np.array([[5,6],[7,8]])
v3 = np.array([[4,5],[2,7]])

np.vstack((v1,v2,v3)) # Stacking v1,v2,v3 on top of each other where first array's element are placed on top

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [4, 5],
       [2, 7]])

***Vertical Stacking Result A Array Where Element Of Previous Array Are Stacked on top of each other by following rule of first traversed will be on top***

***Arrays must have the same number of columns***<br>
***Think of it as stacking rows one under the another***

_____________________________________________________________________________________________________________________________

### ***Horizontal Stacking***

***Same As Verical Stacking But Works In Horizontal Way***

***Here Stacking Happens Along Sideways<br>***
***One Can Imagine Two Arrays Placed Side By Side And Element Are Merge Together And Placed Side By Side On Same Row In New Array<br> Imagine 'a' matrix and 'b' matrix which are hstack if 'a' is placed on left, then element of first row of 'a' are merge with element of first row of 'b' to form a combine row for new matrix , same follows for second, thrid and next ones***<br><br>
***Note:-Stacking Always Works On Array With Same Number Of Rows***

In [ ]:
# Horizontal Stack
h1 = np.array([[1,2],[3,4]])
h2 = np.array([[5,6],[7,8]])

np.hstack((h1,h2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
h1 = np.arange(6).reshape(2,3)
h2 = np.arange(12).reshape(3,4)

np.hstack((h1,h2))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

#### ***Large Example For Understanding***

In [ ]:
v1 = np.random.randint(0, 10, size=(2, 3, 3, 3))
print(v1)
print()
v2 = np.random.randint(0,10,size=(2,3,3,3))
print(v2)

[[[[0 6 4]
   [6 9 8]
   [9 1 3]]

  [[8 9 7]
   [5 3 2]
   [8 0 8]]

  [[3 7 6]
   [3 9 3]
   [2 6 0]]]


 [[[2 7 4]
   [9 9 5]
   [6 1 9]]

  [[5 6 6]
   [5 1 8]
   [6 4 7]]

  [[1 2 9]
   [0 2 2]
   [0 4 2]]]]

[[[[8 8 5]
   [1 1 8]
   [0 4 4]]

  [[9 4 8]
   [0 0 8]
   [4 2 9]]

  [[6 3 3]
   [7 8 9]
   [0 8 7]]]


 [[[0 5 6]
   [4 6 8]
   [8 5 4]]

  [[3 0 7]
   [5 9 2]
   [4 0 3]]

  [[0 3 1]
   [9 7 8]
   [3 9 1]]]]


In [ ]:
np.vstack((v1,v2))

array([[[[0, 6, 4],
         [6, 9, 8],
         [9, 1, 3]],

        [[8, 9, 7],
         [5, 3, 2],
         [8, 0, 8]],

        [[3, 7, 6],
         [3, 9, 3],
         [2, 6, 0]]],


       [[[2, 7, 4],
         [9, 9, 5],
         [6, 1, 9]],

        [[5, 6, 6],
         [5, 1, 8],
         [6, 4, 7]],

        [[1, 2, 9],
         [0, 2, 2],
         [0, 4, 2]]],


       [[[8, 8, 5],
         [1, 1, 8],
         [0, 4, 4]],

        [[9, 4, 8],
         [0, 0, 8],
         [4, 2, 9]],

        [[6, 3, 3],
         [7, 8, 9],
         [0, 8, 7]]],


       [[[0, 5, 6],
         [4, 6, 8],
         [8, 5, 4]],

        [[3, 0, 7],
         [5, 9, 2],
         [4, 0, 3]],

        [[0, 3, 1],
         [9, 7, 8],
         [3, 9, 1]]]])

In [ ]:
np.hstack((v1,v2))

array([[[[0, 6, 4],
         [6, 9, 8],
         [9, 1, 3]],

        [[8, 9, 7],
         [5, 3, 2],
         [8, 0, 8]],

        [[3, 7, 6],
         [3, 9, 3],
         [2, 6, 0]],

        [[8, 8, 5],
         [1, 1, 8],
         [0, 4, 4]],

        [[9, 4, 8],
         [0, 0, 8],
         [4, 2, 9]],

        [[6, 3, 3],
         [7, 8, 9],
         [0, 8, 7]]],


       [[[2, 7, 4],
         [9, 9, 5],
         [6, 1, 9]],

        [[5, 6, 6],
         [5, 1, 8],
         [6, 4, 7]],

        [[1, 2, 9],
         [0, 2, 2],
         [0, 4, 2]],

        [[0, 5, 6],
         [4, 6, 8],
         [8, 5, 4]],

        [[3, 0, 7],
         [5, 9, 2],
         [4, 0, 3]],

        [[0, 3, 1],
         [9, 7, 8],
         [3, 9, 1]]]])

_____________________________________________________________________________________________________________________________

#### ***Spliting***

*There Are Two Major Function For Spliting Array ***'np.split(array,section/tuple)'*** .*<br>
*.split() function takes first argument as array(given array) and second as 'Integer value' for dividing in section or 'tuple' for cutting and dividing across two points or multiple points in array*

In [87]:
array1 = np.array([[5,7,4,36],[7,4,2,6]])
np.split(array1,2)

[array([[ 5,  7,  4, 36]]), array([[7, 4, 2, 6]])]

In [88]:
np.split(array1,4,axis = 1)

[array([[5],
        [7]]),
 array([[7],
        [4]]),
 array([[4],
        [2]]),
 array([[36],
        [ 6]])]

In [89]:
array1 = np.array([[5,7,4,36],[7,4,2,6]],dtype = 'int8')
np.split(array1,(1,4))

[array([[ 5,  7,  4, 36]], dtype=int8),
 array([[7, 4, 2, 6]], dtype=int8),
 array([], shape=(0, 4), dtype=int8)]

***Remember :- spliting always divide in equal part otherwise gives an error***<br>
***for error free code use np.array_split() function same as split but handles extra element when divided uneqauly and also doesn't gives error***

##### ***array.split()***

In [94]:
np.array_split(array1,(2,1))

[array([[ 5,  7,  4, 36],
        [ 7,  4,  2,  6]], dtype=int8),
 array([], shape=(0, 4), dtype=int8),
 array([[7, 4, 2, 6]], dtype=int8)]

#### ***Spliting Horizontally***

***using .hspilt(array,section) use can split array horizontally***

*This function has two arguments first is array and second is section it takes input as int or tuple*<br><br>
*Int For how much section do you want*<br><br>
*Tuple is for spliting array in three parts where tuple is worked as start and stop split makes one cut at start point(from tuple) in array aand at end point(from tuple) in array.Then it split array into three part one from array's start to tuple's start-1 second is from tuple's start to tuple's end-1 and third is from tuple's end to array's end*<br>


In [ ]:
array = np.array([[1,2,3,4],[6,7,8,9]])
print(array)

[[1 2 3 4]
 [6 7 8 9]]


# *Miscellaneous*

Load Data From File 

In [ ]:
import os
print(os.getcwd()) # Get File Location using os module

c:\Users\user\DS\NumPy


In [ ]:
with open("datafile.txt","r")as f :
    print(f.readlines())
    array = f

['42,21,19,29,12,89,48,59,24,34,56,39,4,14,98,86,78,31,73,84,99,58,98,24\n', '31,32,66,36,82,70,4,16,71,62,90,12,2,18,6,22,12,47,0,33,52,91,99,54\n', '29,43,75,27,60,71,73,22,4,67,29,23,88,6,55,4,4,73,0,39,96,49,72,79\n', '13,22,14,99,7,18,69,16,4,98,32,89,27,75,15,53,67,65,48,84,8,2,14,32\n', '32,46,75,12,86,75,6,63,97,31,94,58,13,23,52,35,3,64,40,95,31,1,30,58\n', '5,4,13,41,75,38,73,44,82,31,3,40,13,58,62,70,15,60,74,13,34,42,93,84\n', '38,55,62,87,10,43,0,30,90,51,55,1,54,12,62,30,51,74,69,86,78,51,57,55\n']


In [ ]:
print(array)

<_io.TextIOWrapper name='datafile.txt' mode='r' encoding='utf-8'>


In [ ]:
data = np.genfromtxt('datafile.txt',delimiter = ',',dtype = 'int16')
data

array([[42, 21, 19, 29, 12, 89, 48, 59, 24, 34, 56, 39,  4, 14, 98, 86,
        78, 31, 73, 84, 99, 58, 98, 24],
       [31, 32, 66, 36, 82, 70,  4, 16, 71, 62, 90, 12,  2, 18,  6, 22,
        12, 47,  0, 33, 52, 91, 99, 54],
       [29, 43, 75, 27, 60, 71, 73, 22,  4, 67, 29, 23, 88,  6, 55,  4,
         4, 73,  0, 39, 96, 49, 72, 79],
       [13, 22, 14, 99,  7, 18, 69, 16,  4, 98, 32, 89, 27, 75, 15, 53,
        67, 65, 48, 84,  8,  2, 14, 32],
       [32, 46, 75, 12, 86, 75,  6, 63, 97, 31, 94, 58, 13, 23, 52, 35,
         3, 64, 40, 95, 31,  1, 30, 58],
       [ 5,  4, 13, 41, 75, 38, 73, 44, 82, 31,  3, 40, 13, 58, 62, 70,
        15, 60, 74, 13, 34, 42, 93, 84],
       [38, 55, 62, 87, 10, 43,  0, 30, 90, 51, 55,  1, 54, 12, 62, 30,
        51, 74, 69, 86, 78, 51, 57, 55]], dtype=int16)

In [ ]:
# Boolean Masking
# Advanced Indexing
data>50

array([[False, False, False, False, False,  True, False,  True, False,
        False,  True, False, False, False,  True,  True,  True, False,
         True,  True,  True,  True,  True, False],
       [False, False,  True, False,  True,  True, False, False,  True,
         True,  True, False, False, False, False, False, False, False,
        False, False,  True,  True,  True,  True],
       [False, False,  True, False,  True,  True,  True, False, False,
         True, False, False,  True, False,  True, False, False,  True,
        False, False,  True, False,  True,  True],
       [False, False, False,  True, False, False,  True, False, False,
         True, False,  True, False,  True, False,  True,  True,  True,
        False,  True, False, False, False, False],
       [False, False,  True, False,  True,  True, False,  True,  True,
        False,  True,  True, False, False,  True, False, False,  True,
        False,  True, False, False, False,  True],
       [False, False, False, False,

In [ ]:
data>=50

array([[False, False, False, False, False,  True, False,  True, False,
        False,  True, False, False, False,  True,  True,  True, False,
         True,  True,  True,  True,  True, False],
       [False, False,  True, False,  True,  True, False, False,  True,
         True,  True, False, False, False, False, False, False, False,
        False, False,  True,  True,  True,  True],
       [False, False,  True, False,  True,  True,  True, False, False,
         True, False, False,  True, False,  True, False, False,  True,
        False, False,  True, False,  True,  True],
       [False, False, False,  True, False, False,  True, False, False,
         True, False,  True, False,  True, False,  True,  True,  True,
        False,  True, False, False, False, False],
       [False, False,  True, False,  True,  True, False,  True,  True,
        False,  True,  True, False, False,  True, False, False,  True,
        False,  True, False, False, False,  True],
       [False, False, False, False,

In [ ]:
data[data>50] # This Gives Values Which Are Greater Than 50 or given value

array([89, 59, 56, 98, 86, 78, 73, 84, 99, 58, 98, 66, 82, 70, 71, 62, 90,
       52, 91, 99, 54, 75, 60, 71, 73, 67, 88, 55, 73, 96, 72, 79, 99, 69,
       98, 89, 75, 53, 67, 65, 84, 75, 86, 75, 63, 97, 94, 58, 52, 64, 95,
       58, 75, 73, 82, 58, 62, 70, 60, 74, 93, 84, 55, 62, 87, 90, 51, 55,
       54, 62, 51, 74, 69, 86, 78, 51, 57, 55], dtype=int16)

In [ ]:
# identify any value in this data 's columns is greater 80
np.any(data>80,axis=0)

array([False, False, False,  True,  True,  True, False, False,  True,
        True,  True,  True,  True, False,  True,  True, False, False,
       False,  True,  True,  True,  True,  True])

In [ ]:
# Here axis = 0 represent row-wise iteration and which every row has any element greater than 80 is stored as true other
# who are'nt are stored as false
# You Can Also Check That All Element are greater than 80 or not using

np.all(data>80,axis=0)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [ ]:
# Conditonal Indexing
(data>40) & (data<80)

array([[ True, False, False, False, False, False,  True,  True, False,
        False,  True, False, False, False, False, False,  True, False,
         True, False, False,  True, False, False],
       [False, False,  True, False, False,  True, False, False,  True,
         True, False, False, False, False, False, False, False,  True,
        False, False,  True, False, False,  True],
       [False,  True,  True, False,  True,  True,  True, False, False,
         True, False, False, False, False,  True, False, False,  True,
        False, False, False,  True,  True,  True],
       [False, False, False, False, False, False,  True, False, False,
        False, False, False, False,  True, False,  True,  True,  True,
         True, False, False, False, False, False],
       [False,  True,  True, False, False,  True, False,  True, False,
        False, False,  True, False, False,  True, False, False,  True,
        False, False, False, False, False,  True],
       [False, False, False,  True,

In [ ]:
# You Can Also Obtain Numbers which follows this condition bytearray
data[(data>40) & (data<80)]
# or
data[((data>40) & (data<80))]

array([42, 48, 59, 56, 78, 73, 58, 66, 70, 71, 62, 47, 52, 54, 43, 75, 60,
       71, 73, 67, 55, 73, 49, 72, 79, 69, 75, 53, 67, 65, 48, 46, 75, 75,
       63, 58, 52, 64, 58, 41, 75, 73, 44, 58, 62, 70, 60, 74, 42, 55, 62,
       43, 51, 55, 54, 62, 51, 74, 69, 78, 51, 57, 55], dtype=int16)

In [ ]:
# Using Not Operator '~'
(~((data>40) & (data<80)))

array([[False,  True,  True,  True,  True,  True, False, False,  True,
         True, False,  True,  True,  True,  True,  True, False,  True,
        False,  True,  True, False,  True,  True],
       [ True,  True, False,  True,  True, False,  True,  True, False,
        False,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True, False,  True,  True, False],
       [ True, False, False,  True, False, False, False,  True,  True,
        False,  True,  True,  True,  True, False,  True,  True, False,
         True,  True,  True, False, False, False],
       [ True,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True,  True,  True, False,  True, False, False, False,
        False,  True,  True,  True,  True,  True],
       [ True, False, False,  True,  True, False,  True, False,  True,
         True,  True, False,  True,  True, False,  True,  True, False,
         True,  True,  True,  True,  True, False],
       [ True,  True,  True, False,

*You Can Index with a list in Numpy*

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a[[1,2,6]]) 
# Here First Square Bracket (Outer) Is for accessing a's array and second one is for generating list of element of array 'a' 
# at given index

[2 3 7]


## ***Day4 Numpy Notes***

### ***Advanced Indexing***

**There Are Two Types Of Advanced Array Indexing**<br>
* *Integer Array Indexing*<br>
* *Boolean Array Indexing*

***Integer Array Indexing***

*Integer array indexing refers to selecting elements from an N-dimensional array using another array of integers, where each integer or set of integers specifies a position along a particular axis.*

For Example:-

In [95]:
x = np.arange(3,28).reshape(5,5)
print(x)
print(x[3,4])

x[np.array([3,4,1])] # Here rows of array x are consider array and as per number's of column it gives us that ath row from array x

[[ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]
 [18 19 20 21 22]
 [23 24 25 26 27]]
22


array([[18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27],
       [ 8,  9, 10, 11, 12]])

In [ ]:
x=np.array([[1,2],[3,4],[5,6]])
x[np.array([1,2]),np.array([0])]

array([3, 5])

*Integer indexing in NumPy extends basic indexing by using arrays of integers to specify explicit positions across one or more dimensions. Each integer (or set of integers) is used in coordination with others to select specific elements.*

*The result is a new array , a copy of the original data, not a view—constructed by iterating over these index combinations.*

*Remember If index value are out of bounds then is throws a IndexError*

*When performing indexing on an N-dimensional array using N separate integer arrays, NumPy treats each integer array as specifying indices along a particular axis. It then performs element-wise selection by combining the corresponding elements from each index array, extracting values from those coordinated positions.*

In [ ]:
x = np.arange(0,100).reshape(10,10) # 2D Array
print(x)
x[np.array([1,2,5,8]),np.array([3,4,6,7])] # Two-Integer array used for indexing

# Array Used Here Are Interpreted as x[r,c] where r and c are integer array used for indexing
# As There Are 4 elements in indexing integer array there are 4 output corresponding to each pair

# 1<->3 --> 13 , 2<->4 --> 24 , 5<->6 --> 56 , 8<->7 --> 87

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


array([13, 24, 56, 87])

*Lets Try To Pair Different Size Of Array With Each Other*

In [ ]:
x[np.array([2,3,4]),np.array([5,6,7,8])]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (4,) 

*This Gives A Shape Mismatched Error means broadcasting is not possible here*<br>

*Important Point :- When There N Integer Indexing Array for N Dimensional Array, then Resultant Output Is Same Size As Size of Indexing Arrays*

* *When Combining Integer Indexing Array with scalar,
 broadcasting is used to *

In [ ]:
x[np.array([2,5]),0] # Accessing Element from array with one index is fix or one index is scalar
# Accessing element with index from 2 and 5 in first row (ex:- c = 0)

array([20, 50])

#### **Advanced Integer Indexing Examples And Their Exaplanation**

***This Examples Are Mainly Problems Or Harder Examples***

* ***Integer Array Indexing***

*Ex1:-Code To Find specific element from every row of an array*

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
print(a[[0,1,2],[0,0,0]]) # Accessing first element from every row using [0,1,2] represents first,second,third rows
# OR
print(a[:,0])

[1 3 5]
[1 3 5]


**Above Example Represents How To Access List Out Of Larger Array Using Advanced Indexing**

*Ex2:-More Complex Form of Indexing*

In [ ]:
print(a[:,[0,1,1]]) 

# [[1,2]   <- c1
#  [3,4]   <- c2
#  [5,6]]  <- c3
# a[:,[0,1,1]] -> ':' hepls to traverse along rows , '[0,1,1]' hepls to select specific element from each traversed rows


[[1 2 2]
 [3 4 4]
 [5 6 6]]


In [ ]:
#  [0,1,1]     <- indexing array 

# [[1 2 2]     <- first row's [first,second,second] element using indexing array
#  [3 4 4]
#  [5 6 6]]

*Ex3:-From a 6x5 array the corner elements should be selected using advanced indexing.*

In [ ]:
a = np.arange(1,31).reshape(6,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [ ]:
# Answer:-
a[[0,0,5,5],[0,4,0,4]].reshape(2,2)
# Here We Use two integer array for indexing corner element in original array

array([[ 1,  5],
       [26, 30]])

In [ ]:
# Another Way To Do
a[[[0,0],[5,5]],[[0,4],[0,4]]]

array([[ 1,  5],
       [26, 30]])

##### **Broadcasting(Short Introduction)**

***Broadcasting descibes how numpy treats arrays with different shaped during arithmatic operations***

*Smaller Array Are Broadcasted over larger array for there shape compatibilty*<br>
*It Stretches smaller array over larger ones*<br>

*Streching is a conceptual Numpy doesn't make copies of smaller array it uses original array efficently*

In [ ]:
a = np.array([[6,7,8,3,7,5],[2,4,6,4,8,3]])
print(a)
b = np.array([7,8,9,2])
print(b)

a*b


[[6 7 8 3 7 5]
 [2 4 6 4 8 3]]
[7 8 9 2]


ValueError: operands could not be broadcast together with shapes (2,6) (4,) 

*Here Multiplication is not possible due to mismatched dimenstions between two np arrays*<br><br>
*In This Case Broadcasting Also Does Not Works Due To inefficient streching*<br><br>
*Here b array also cannot be broadcasted due to mismatched size of broadcastor and broadcasting array*<br><br>
*b array has 4 element but the a array's first element which is an array has 6 element so if we multiply first 4 element there will be two element still there which result error*<br><br>
*If there will be 6 element in b array each element can be broadcasted over entire a's array , where it has two elements which are indeed array with 6 elements*

In [ ]:
c = np.array([4,7,2,7,3,0])# Here We will make array of 6 element which can be broadcsted over entire a array
a*c

array([[24, 49, 16, 21, 21,  0],
       [ 8, 28, 12, 28, 24,  0]])

*Broadcasting works by multiplying a's first element(array:-[6,7,8,3,7,5]) also with a's second element(array:-[2,4,6,4,8,3])*

**np.newaxis()**

*.newaxis() allows to add new axis or new dimension , how we want*

In [ ]:
o = np.array([1,2,3])
o.shape


(3,)

In [ ]:
p=o[np.newaxis,np.newaxis,:]
print(p)
p.shape


[[[1 2 3]]]


(1, 1, 3)

## **Day5 Numpy Notes**

***Boolean Array Indexing***

*In this type of advanced array indexing obj is an array of boolean type , they can be intered directly or can be obtained by comparing cases to get output a boolean value*

In [ ]:
x = np.array([[1.2,2.3],[4.5,5.6],[6.7,7.8]]) 

In [ ]:
x>4.5  

array([[False, False],
       [False,  True],
       [ True,  True]])

*This Expression Compares each value of x with given condition to store in array with boolean data tyep*

*The stored array is of same size as x , but each value of x is compared and is stored in form of true or false*

In [ ]:
o = np.array([4,6,2,np.nan,np.nan,1,4])
o[~np.isnan(o)] # Outputs Value Which Are Not Of nan type

# np.nana is none type of data type in numpy

array([4., 6., 2., 1., 4.])

***Or It Can Also Be Used To Filter Number For Particular Condition To Operate Them Afterward***

In [ ]:
u = np.arange(3,58,2).reshape(7,4)
print(u)

[[ 3  5  7  9]
 [11 13 15 17]
 [19 21 23 25]
 [27 29 31 33]
 [35 37 39 41]
 [43 45 47 49]
 [51 53 55 57]]


In [ ]:
u[u%3 == 0]

array([ 3,  9, 15, 21, 27, 33, 39, 45, 51, 57])

*Here We Have Filtered Numbers Which Are Divisible By 3 From Larger Set Of Data*

#### **Advanced Boolean Indexing Examples And Their Exaplanation**

*Ex1:- From an array , select all rows which sum up to less or equal to two*

In [ ]:
x = np.array([[0, 1], [1, 1], [2, 2]])
row = np.sum(x,axis=1)
x[row<=2]

array([[0, 1],
       [1, 1]])

*Ex2:-Use Boolean indexing to select all rows adding upto an even number with column 0 ,2 should be selected with advanced integer indexing*

In [ ]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])

In [ ]:
rowssum = np.sum(x,axis=1)
print(rowssum)
rows = rowssum % 2 == 0
columns = [0,2]
x[np.ix_(rows,columns)]

[ 3 12 21 30]


array([[ 3,  5],
       [ 9, 11]])

***Combining Advanced And Basic Indexing***

*When We Use at least one slice ':' , ellipse '...' in the index , such type of indexing is state as complex or combinational indexing*

*Where Both Advanced And Basic Indexing Works Independently to get required output*

In [ ]:
y = np.arange(1,36).reshape(5,7)
print(y)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]]


In [ ]:
y[np.array([2,4,3]),0:2] 
# Here Integer Indexing and slicing Works independently 

array([[15, 16],
       [29, 30],
       [22, 23]])

In [ ]:
# Also Can be done by
y[np.array([2,4,3]),:][:,1:3]

array([[16, 17],
       [30, 31],
       [23, 24]])

Ex1:-

In [ ]:
x = np.arange(35).reshape(5, 7)
b = x>20
b

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [ ]:
x[b[:,5],1:3]

array([[22, 23],
       [29, 30]])

*Boolean Array Indexing Is Used With Slicing ndarrays for complex outputs*

*So Combination Indexing Refers to complex indexing which invauls multiple types of indexing*

### *Field Access*

*If the ndarray object is a structured array the fields of the array can be accessed by indexing the array with strings, dictionary-like.*

In [ ]:
x = np.zeros((2, 2), dtype=[('a', np.int32), ('b', np.float64, (3, 3))])
print(x)
x['a'].shape

[[(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]
 [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]]


(2, 2)

In [ ]:
x['a'].dtype

dtype('int32')

In [ ]:
x['b'].shape

(2, 2, 3, 3)

In [ ]:
x['b'].dtype

dtype('float64')

## *I/O In Numpy*

*Note: NumPy supports I/O with .npy and .txt files (np.load, np.save, np.loadtxt), but this is rarely used directly when working with Pandas or full datasets.*

### ***np.save()***

*Save an array to a binary file in NumPy .npy format.*

In [ ]:
np.save('file2',np.array([[9,6,4],[3,6,3]]))
np.load('file2.npy')

array([[9, 6, 4],
       [3, 6, 3]])

In [ ]:
from tempfile import TemporaryFile
outfile = TemporaryFile()
x = np.arange(30)
np.save(outfile,x)
_ = outfile.seek(0)  # Need to stimulate closing and reopening of file
np.load(outfile)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

### ***np.load()***

*Load arrays or pickled objects from .npy, .npz or pickled files.*

In [ ]:
np.save('file3',np.random.randint(2,100,size=(8,9))/10)
np.load('file3.npy')

array([[5.9, 1.8, 6.3, 8. , 9.2, 5.3, 4.5, 2.9, 4.3],
       [3.9, 2.8, 1.4, 2.8, 6.8, 3.3, 7.6, 4.3, 5.3],
       [6.2, 2.9, 7.9, 3.4, 4.5, 6.7, 7.9, 0.5, 2.4],
       [0.6, 7.1, 6.5, 9.3, 3.7, 5.5, 8.1, 1.8, 0.9],
       [5.1, 6.8, 3.3, 2.8, 1.9, 6.2, 0.6, 1.7, 0.4],
       [2.3, 8.4, 7.1, 2.2, 7. , 1.8, 8.6, 5.1, 1.3],
       [5.8, 7.1, 2.2, 2.6, 3.7, 3.4, 1.2, 9.3, 6.1],
       [7.9, 6.5, 6.9, 8.3, 3.8, 2. , 0.2, 1.5, 0.5]])

### ***np.loadtxt()***

*Load Data From Text File*<br><br>
*Syntax:- np.loadtxt('filename','dtype','delimeter')*<br>
* *filename:- Name of file , path of file(with name) , or list* <br>
* *dtype:-Data-type of resulting array (deafult:-float)*<br>
* *delimeter:-The character used to separate the values.*

*There are multiple argument but this three are most used*

In [96]:
from io import StringIO
c = StringIO("1,1.3,8.9")
data = np.loadtxt(c,delimiter=",")
print(data)

[1.  1.3 8.9]


In [98]:
c = StringIO("11.38.9")
data2 = np.loadtxt(c,delimiter='.')
print(data2)


[11. 38.  9.]


### ***np.getfromtxt()***

*Load Data From a Text File, with missing values handled as specified*<br>
*Syntax:-np.genfromtxt('filename','dtype','delimeter=,')*<br>
* *filename:-File, filename, list, or generator to read.*<br>
* *dtype:-Data type of the resulting array.* 

In [ ]:
s = StringIO("1,1.3,abcde")
data = np.genfromtxt(s, dtype=[('myint','i8'),('myfloat','f8'),
('mystring','S5')], delimiter=",")
data

array((1, 1.3, b'abcde'),
      dtype=[('myint', '<i8'), ('myfloat', '<f8'), ('mystring', 'S5')])

### ***Argument Table For getfromtxt()***

| **Arguments** | **What They Do** | **How To Use** |
|---|---|---|
| fname | Path to the file | np.getfromtxt(fname = 'filename.ext')|
| delimiter | String Used To Seperate values | np.getfromtxt(delimiter = ' "character" ')|
| dtype | Data-Type of resulting array | np.getfromtxt(dtype = 'float')|
| skipheader | The number of lines to skip at the beginning of the file. | np.getfromtxt(skipheader = '1')|
| usecols | Load selected columns only | np.getfromtxt(usecols = [0,1])|

## ***Sorting ,Searching And Counting Functions***

### ***numpy.sort()***

*It Returns Sorted Copy Of Given Array*<br>
*Has two major arguments .sort(array,axis=-1)*

In [ ]:
a = np.random.randint(0,10,size = (9))
print(a)
print(np.sort(a))

[6 5 7 7 2 8 8 6 6]
[2 5 6 6 6 7 7 8 8]


In [ ]:
b = np.random.randint(0,14,size=(2,7))
print(b)
print(np.sort(b))

[[ 4  3  3  0  1  7  2]
 [ 7  8  2 10 11  7 10]]
[[ 0  1  2  3  3  4  7]
 [ 2  7  7  8 10 10 11]]


### ***numpy.argsort()***

*Returns indices of element of sorted array in original array*

In [ ]:
print(np.sort(a))
print(np.argsort(a))

[2 5 6 6 6 7 7 8 8]
[4 1 0 7 8 2 3 5 6]


### ***numpy.ndarray.sort()***

*Sorts An N Dimenstional array*

*Same as numpy.sort but it act as array attribute not as numpy function*

In [ ]:
a.sort
a

array([6, 5, 7, 7, 2, 8, 8, 6, 6])

Has axis as parameter to perform action along that row

### ***numpy.partition()***

*Divides The Array At Given Index where element left to that index are < array[index] and element right to that index are > or equal to array[index]*

*It Has Two Arguments array , position of partition and axis*

In [ ]:
k = np.random.randint(10,99,size = (90))
k

array([50, 41, 94, 97, 64, 18, 75, 12, 56, 61, 92, 94, 11, 34, 55, 29, 29,
       49, 47, 36, 86, 43, 91, 30, 63, 93, 30, 26, 66, 23, 28, 21, 24, 89,
       64, 65, 37, 83, 60, 22, 77, 18, 12, 54, 47, 95, 16, 68, 66, 92, 32,
       19, 16, 40, 36, 73, 52, 61, 74, 93, 98, 17, 30, 93, 84, 75, 33, 70,
       45, 89, 75, 55, 38, 71, 24, 81, 39, 53, 38, 62, 44, 47, 47, 34, 39,
       75, 97, 28, 85, 21])

In [ ]:
np.partition(k,61)

array([18, 21, 28, 39, 34, 18, 47, 12, 47, 44, 38, 39, 11, 34, 24, 29, 29,
       38, 45, 36, 33, 43, 30, 30, 17, 36, 30, 26, 40, 23, 28, 21, 24, 16,
       19, 32, 37, 16, 41, 22, 12, 47, 47, 49, 55, 53, 54, 52, 50, 55, 56,
       64, 61, 60, 61, 63, 62, 64, 65, 66, 66, 68, 70, 71, 73, 74, 75, 75,
       75, 75, 89, 86, 84, 93, 91, 81, 94, 98, 92, 93, 93, 89, 92, 83, 97,
       95, 97, 94, 85, 77])

*Creates a copy of the array and partially sorts it in such a way that the value of the element in k-th position is in the position it would be in a sorted array. In the output array, all elements smaller than the k-th element are located to the left of this element and all equal or greater are located to its right.*

### ***numpy.argpartition()***

*Returns an array of indices of the same shape as a that index data along the given axis in partitioned order.*

*Same As Partition but returns indices of *

In [ ]:
x = np.array([3,9,7,5,38,2, 4, 2, 1])
np.argpartition(x,3)
x[np.argpartition(x,3)]

array([ 2,  1,  2,  3,  9,  5,  4,  7, 38])

*Which Can Be Further Used In Indexing*

### ***numpy.maximum()***

*This Function Returns element-wise maximum value between two array*

In [ ]:
print(x)
y = np.random.randint(2,17,size=(9))
print(y)

np.maximum(x,y) # Returns element wise largest value from both the arrays

[ 3  9  7  5 38  2  4  2  1]
[15  4  3  7  4  2  8  9  4]


array([15,  9,  7,  7, 38,  2,  8,  9,  4])

### ***numpy.argmax() & numpy.argmin()***

* *numpy.argmax( array , axis ):-Returns Indices of maximum value in array*

* *numpy.argmin( array , axis) :- Returns Indices of minimum value in array*

In [ ]:
print(np.argmax(x))
print(np.argmin(x))

4
8


### ***numpy.argwhere()***

*Find the indices of array elements that are non-zero, grouped by element.*

In [ ]:
x = np.arange(6).reshape(2,3)
np.argwhere(x>1)

array([[0, 2],
       [1, 0],
       [1, 1],
       [1, 2]], dtype=int64)

*Indices of elements that are non-zero. Indices are grouped by element. This array will have shape (N, a.ndim) where N is the number of non-zero items.*

### ***numpy.where() :- very important***

In [ ]:
a = np.array([93,6,9,3,0,4,256,0,5,34,9])
x = 3
np.where(a<200,a,-1)

array([93,  6,  9,  3,  0,  4, -1,  0,  5, 34,  9])

* *When Used x,y  x is return if condition is true otherwise y is returned*

* *Returns An Array Where Elements from x condition is true and element from y elsewhere*

In [ ]:
l = np.random.randint(0,100,size=(6,9))
l

array([[72, 97,  5, 42, 40,  7, 68, 61,  1],
       [95, 30,  9, 98, 36, 25,  1, 62, 98],
       [39, 95, 24, 66,  2, 78, 66, 46, 40],
       [25, 27, 23, 23, 79, 13, 65, 57, 29],
       [33, 70, 77, 96, 59, 12, 28, 56, 34],
       [48, 81, 91, 35, 50, 36, 12, 93, 17]])

In [ ]:
np.where(l%2 == 0,True,False)

array([[ True, False, False,  True,  True, False,  True, False, False],
       [False,  True, False,  True,  True, False, False,  True,  True],
       [False, False,  True,  True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False, False, False, False],
       [False,  True, False,  True, False,  True,  True,  True,  True],
       [ True, False, False, False,  True,  True,  True, False, False]])

In [ ]:
np.where((l<20) & (l>6), "6.20","0.5--21.100" )

array([['0.5--21.100', '0.5--21.100', '0.5--21.100', '0.5--21.100',
        '0.5--21.100', '6.20', '0.5--21.100', '0.5--21.100',
        '0.5--21.100'],
       ['0.5--21.100', '0.5--21.100', '6.20', '0.5--21.100',
        '0.5--21.100', '0.5--21.100', '0.5--21.100', '0.5--21.100',
        '0.5--21.100'],
       ['0.5--21.100', '0.5--21.100', '0.5--21.100', '0.5--21.100',
        '0.5--21.100', '0.5--21.100', '0.5--21.100', '0.5--21.100',
        '0.5--21.100'],
       ['0.5--21.100', '0.5--21.100', '0.5--21.100', '0.5--21.100',
        '0.5--21.100', '6.20', '0.5--21.100', '0.5--21.100',
        '0.5--21.100'],
       ['0.5--21.100', '0.5--21.100', '0.5--21.100', '0.5--21.100',
        '0.5--21.100', '6.20', '0.5--21.100', '0.5--21.100',
        '0.5--21.100'],
       ['0.5--21.100', '0.5--21.100', '0.5--21.100', '0.5--21.100',
        '0.5--21.100', '0.5--21.100', '6.20', '0.5--21.100', '6.20']],
      dtype='<U11')