## ***Numpy Practice Set***

In [27]:
import numpy as np

#### Q1:-How To Make 1D Array from ranging 0 to 9

In [28]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Q2:-Create a 3×3 numpy array of all True’s

In [29]:
b = np.ones((3,3),dtype = 'bool')
b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#### Q3:-Extract all odd numbers from arr <br>

#### arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

#### Q4:-Replace all odd numbers in arr with -1

In [31]:
arr = np.arange(0,10)
newarr = np.copy(arr)

newarr[newarr%2 == 1] = -1
print("Original:-",arr)
print("New Array:-",newarr)

Original:- [0 1 2 3 4 5 6 7 8 9]
New Array:- [ 0 -1  2 -1  4 -1  6 -1  8 -1]


Q5:-Convert a 1D array to a 2D array with 2 rows

In [32]:
np.arange(10).reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Q6:-Stack arrays a and b vertically<br>
a = np.arange(10).reshape(2,-1)<br>
b = np.repeat(1, 10).reshape(2,-1)


In [33]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Q7:- Stack arrays a and b horizontally

In [34]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.hstack((a,b))

array([[0, 1, 2, ..., 1, 1, 1],
       [5, 6, 7, ..., 1, 1, 1]])

Q8:-Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

In [35]:
a = np.array([1,2,3])
r1 = np.repeat(a,3,axis = 0)
print(r1)
r2 = np.tile(a,3)
r2

np.hstack((r1,r2))

[1 1 1 2 2 2 3 3 3]


array([1, 1, 1, ..., 1, 2, 3])

Q9:-Get the common items between a and b

In [36]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

Q11:-How to remove element from one array those exist in another

In [37]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.setdiff1d(a,b)

array([1, 3, 5, 6])

Q12:-How to get the position where elements of two arrays match

In [38]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

Q13:- How to extract all numbers between a given range from a numpy array ?

In [39]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>=5) & (a<=10)]

array([ 6,  9, 10])

Q14:-How to make a python function that handles scalars to work on numpy arrays ?

In [40]:
def maxx(a,b):
    return np.maximum(a,b)


a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
maxx(a,b)

array([6, 7, 9, 8, 9, 7, 5])

Q15:-How to swap two columns in a 2d numpy array?

In [41]:
arr = np.arange(9).reshape(3,3)
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

Q16:-How to swap two rows in a 2d numpy array?

In [42]:
arr = np.arange(9).reshape(3,3)
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

Q17:-How to reverse the rows of a 2D array?

In [43]:
arr = np.arange(9).reshape(3,3)
arr[::-1,:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

Q18:-How to reverse the columns of a 2D array?

In [44]:
arr = np.arange(9).reshape(3,3)
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])


Q19:-How to create a 2D array containing random floats between 5 and 10?

In [45]:
arr = np.random.uniform(5,10,size=(5,3))
arr

array([[7.8755, 9.4566, 6.046 ],
       [5.9266, 5.5419, 6.0985],
       [9.8931, 9.0584, 5.8597],
       [9.0811, 6.3704, 7.1585],
       [9.7001, 9.0882, 6.6806]])

Q20:-How to print only 3 decimal places in python numpy array?

In [46]:
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=4)
rand_arr

array([[0.1754, 0.3728, 0.0057],
       [0.2524, 0.7957, 0.0153],
       [0.5988, 0.6038, 0.1051],
       [0.3819, 0.0365, 0.8904],
       [0.9809, 0.0599, 0.8905]])

Q21:-How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

In [47]:
np.random.seed(100)
randomarr = np.random.random([3,3])/1e3
randomarr

array([[5.4340e-04, 2.7837e-04, 4.2452e-04],
       [8.4478e-04, 4.7189e-06, 1.2157e-04],
       [6.7075e-04, 8.2585e-04, 1.3671e-04]])

Q22:-How to limit the number of items printed in output of numpy array?



In [48]:
a = np.arange(15)
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

Q23:-How to print the full numpy array without truncating

In [49]:
np.set_printoptions(threshold=15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Q24:-How to import a dataset with numbers and texts keeping the text intact in python numpy?

In [50]:
iris_data = np.genfromtxt('Iris.csv', delimiter=',',dtype=object)
iris_data

array([[b'Id', b'SepalLengthCm', b'SepalWidthCm', b'PetalLengthCm',
        b'PetalWidthCm', b'Species'],
       [b'1', b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'2', b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       ...,
       [b'148', b'6.5', b'3.0', b'5.2', b'2.0', b'Iris-virginica'],
       [b'149', b'6.2', b'3.4', b'5.4', b'2.3', b'Iris-virginica'],
       [b'150', b'5.9', b'3.0', b'5.1', b'1.8', b'Iris-virginica']],
      dtype=object)

Q25:-How to extract a particular column from 1D array of tuples?

In [ ]:
iris_data[:,-1]


array([b'Species', b'Iris-setosa', b'Iris-setosa', ..., b'Iris-virginica',
       b'Iris-virginica', b'Iris-virginica'], dtype=object)

Q26:-How to convert a 1d array of tuples to a 2d numpy array?

Convert the 1D iris to 2D array iris_2d by omitting the species text field.

In [52]:
iris_data = np.genfromtxt('Iris.csv', delimiter=',',skip_header=1,dtype = 'float',usecols=[0,1,2,3])
iris_data


array([[  1. ,   5.1,   3.5,   1.4],
       [  2. ,   4.9,   3. ,   1.4],
       [  3. ,   4.7,   3.2,   1.3],
       ...,
       [148. ,   6.5,   3. ,   5.2],
       [149. ,   6.2,   3.4,   5.4],
       [150. ,   5.9,   3. ,   5.1]])

Q27:-How to compute the mean, median, standard deviation of a numpy array?

Find the mean, median, standard deviation of iris's sepallength (1st column)

In [60]:
iris_data = np.genfromtxt('Iris.csv',delimiter=',',skip_header=1,usecols=[1])
print("Mean",np.mean(iris_data))
print("Median",np.median(iris_data))
print("Standard Deviation",np.std(iris_data))

Mean 5.843333333333334
Median 5.8
Standard Deviation 0.8253012917851409


Q28:-How to normalize an array so the values range exactly between 0 and 1

Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.

In [64]:
iris_sepal_length = np.genfromtxt('Iris.csv',delimiter=',',skip_header=1,usecols = [1])
(iris_sepal_length-np.min(iris_sepal_length))/(np.max(iris_sepal_length)-np.min(iris_sepal_length))

array([0.2222, 0.1667, 0.1111, ..., 0.6111, 0.5278, 0.4444])

Q29:-How to compute the softmax score?

In [70]:
iris_data = np.genfromtxt('Iris.csv',delimiter=',',skip_header=1,usecols=[1])


Q30:-How to find the percentile scores of a numpy array?

Find the 5th and 95th percentile of iris's sepallength

In [74]:
iris_data = np.genfromtxt('Iris.csv',delimiter=',',skip_header=1,usecols=[1])
iris_data

np.percentile(iris_data,q=[95,5])

array([7.255, 4.6  ])

Q31:-How to insert values at random positions in an array?

Insert np.nan values at 20 random positions in iris_2d dataset

In [82]:
iris_data=np.genfromtxt('Iris.csv',delimiter=',',skip_header=1,usecols=[1,2,3,4,])
for i in np.random.randint(0,len(iris_data),20):
    iris_data[i]=np.nan
iris_data

array([[nan, nan, nan, nan],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       ...,
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

Q32:-How to find the position of missing values in numpy array?

In [ ]:
iris_data = np.genfromtxt('Iris.csv',delimiter='1',skip_header=1,usecols=[])