In [1]:
import numpy as np

#### **Advanced Indexing Examples And Their Exaplanation**

***This Examples Are Mainly Problems Or Harder Examples***

* ***Integer Array Indexing***

*Ex1:-Code To Find specific element from every row of an array*

In [15]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [20]:
print(a[[0,1,2],[0,0,0]]) # Accessing first element from every row using [0,1,2] represents first,second,third rows
# OR
print(a[:,0])

[1 3 5]
[1 3 5]


**Above Example Represents How To Access List Out Of Larger Array Using Advanced Indexing**

*Ex2:-More Complex Form of Indexing*

In [ ]:
print(a[:,[0,1,1]]) 

# [[1,2]   <- c1
#  [3,4]   <- c2
#  [5,6]]  <- c3
# a[:,[0,1,1]] -> ':' hepls to traverse along rows , '[0,1,1]' hepls to select specific element from each traversed rows


[[1 2 2]
 [3 4 4]
 [5 6 6]]


In [ ]:
#  [0,1,1]     <- indexing array 

# [[1 2 2]     <- first row's [first,second,second] element using indexing array
#  [3 4 4]
#  [5 6 6]]

*Ex3:-From a 6x5 array the corner elements should be selected using advanced indexing.*

In [21]:
a = np.arange(1,31).reshape(6,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [51]:
# Answer:-
a[[0,0,5,5],[0,4,0,4]].reshape(2,2)
# Here We Use two integer array for indexing corner element in original array

array([[ 1,  5],
       [26, 30]])

In [52]:
# Another Way To Do
a[[[0,0],[5,5]],[[0,4],[0,4]]]

array([[ 1,  5],
       [26, 30]])