## ***Numpy Practice Set***

In [2]:
import numpy as np

#### Q1:-How To Make 1D Array from ranging 0 to 9

In [3]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Q2:-Create a 3×3 numpy array of all True’s

In [4]:
b = np.ones((3,3),dtype = 'bool')
b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#### Q3:-Extract all odd numbers from arr <br>

#### arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

#### Q4:-Replace all odd numbers in arr with -1

In [6]:
arr = np.arange(0,10)
newarr = np.copy(arr)

newarr[newarr%2 == 1] = -1
print("Original:-",arr)
print("New Array:-",newarr)

Original:- [0 1 2 3 4 5 6 7 8 9]
New Array:- [ 0 -1  2 -1  4 -1  6 -1  8 -1]


Q5:-Convert a 1D array to a 2D array with 2 rows

In [7]:
np.arange(10).reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Q6:-Stack arrays a and b vertically<br>
a = np.arange(10).reshape(2,-1)<br>
b = np.repeat(1, 10).reshape(2,-1)


In [8]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Q7:- Stack arrays a and b horizontally

In [10]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

Q8:-Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

In [24]:
a = np.array([1,2,3])
r1 = np.repeat(a,3,axis = 0)
print(r1)
r2 = np.tile(a,3)
r2

np.hstack((r1,r2))

[1 1 1 2 2 2 3 3 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Q9:-Get the common items between a and b

In [25]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])